#ifndef UE4SS_SDK_Cheat_DoubleDamageMultiplierReceivedGameplayEffect_HPP
#define UE4SS_SDK_Cheat_DoubleDamageMultiplierReceivedGameplayEffect_HPP

class UCheat_DoubleDamageMultiplierReceivedGameplayEffect_C : public UCheat_DamageMultiplierReceivedGameplayEffect_C
{
}; // Size: 0x7F8

#endif
