#ifndef UE4SS_SDK_Cheat_QuadrupleDamageMultiplierReceivedGameplayEffect_HPP
#define UE4SS_SDK_Cheat_QuadrupleDamageMultiplierReceivedGameplayEffect_HPP

class UCheat_QuadrupleDamageMultiplierReceivedGameplayEffect_C : public UCheat_DamageMultiplierReceivedGameplayEffect_C
{
}; // Size: 0x7F8

#endif
