#ifndef UE4SS_SDK_BP_AiCondition_CanPerform_TraversalAttack_HPP
#define UE4SS_SDK_BP_AiCondition_CanPerform_TraversalAttack_HPP

class UBP_AiCondition_CanPerform_TraversalAttack_C : public UComboAIConditionCanPerformAction
{
};

#endif
