#ifndef UE4SS_SDK_BP_AICharacter_FireDisciple_M_HD2_Fighter_01_HPP
#define UE4SS_SDK_BP_AICharacter_FireDisciple_M_HD2_Fighter_01_HPP

class ABP_AICharacter_FireDisciple_M_HD2_Fighter_01_C : public ABP_FireDisciple_Base_C
{
};

#endif
