#ifndef UE4SS_SDK_BP_AICharacter_Servant_W_HD02_Clubber_06_HPP
#define UE4SS_SDK_BP_AICharacter_Servant_W_HD02_Clubber_06_HPP

class ABP_AICharacter_Servant_W_HD02_Clubber_06_C : public ABP_Servant_Base_W_C
{
};

#endif
