#ifndef UE4SS_SDK_BP_AICharacter_Grunt_W_HD2_Fighter_02_HPP
#define UE4SS_SDK_BP_AICharacter_Grunt_W_HD2_Fighter_02_HPP

class ABP_AICharacter_Grunt_W_HD2_Fighter_02_C : public ABP_Grunt_Base_W_C
{
};

#endif
