#ifndef UE4SS_SDK_BP_ArchetypeDefenseTest_FireDisciple_HPP
#define UE4SS_SDK_BP_ArchetypeDefenseTest_FireDisciple_HPP

class UBP_ArchetypeDefenseTest_FireDisciple_C : public UBP_FireDisciple_ArchetypeDB_H2_C
{
};

#endif
