#ifndef UE4SS_SDK_BP_AiCondition_GetUpAttack_Range_HPP
#define UE4SS_SDK_BP_AiCondition_GetUpAttack_Range_HPP

class UBP_AiCondition_GetUpAttack_Range_C : public UComboTransitionConditionTargetDistance
{
};

#endif
