#ifndef UE4SS_SDK_BP_AiAction_Dash_S_Short_FireDisciple_HPP
#define UE4SS_SDK_BP_AiAction_Dash_S_Short_FireDisciple_HPP

class UBP_AiAction_Dash_S_Short_FireDisciple_C : public UBP_AiAction_Dash_S_C
{
};

#endif
