#ifndef UE4SS_SDK_BP_AICharacter_Servant_M_HD02_Junky_01_HPP
#define UE4SS_SDK_BP_AICharacter_Servant_M_HD02_Junky_01_HPP

class ABP_AICharacter_Servant_M_HD02_Junky_01_C : public ABP_Servant_Base_C
{
};

#endif
