#ifndef UE4SS_SDK_BP_AICharacter_FireDisciple_M_HD2_Fighter_02_HPP
#define UE4SS_SDK_BP_AICharacter_FireDisciple_M_HD2_Fighter_02_HPP

class ABP_AICharacter_FireDisciple_M_HD2_Fighter_02_C : public ABP_FireDisciple_Base_C
{
};

#endif
