#ifndef UE4SS_SDK_BP_AiCondition_FindWJToTarget_FireDisciple_HPP
#define UE4SS_SDK_BP_AiCondition_FindWJToTarget_FireDisciple_HPP

class UBP_AiCondition_FindWJToTarget_FireDisciple_C : public UBP_AiCondition_FindWJToTarget_Vertical_C
{
};

#endif
