#ifndef UE4SS_SDK_BP_AICondition_IsFrozenBySanctuary_HPP
#define UE4SS_SDK_BP_AICondition_IsFrozenBySanctuary_HPP

class UBP_AICondition_IsFrozenBySanctuary_C : public UComboAIConditionIsFrozenBySanctuary
{
};

#endif
