#ifndef UE4SS_SDK_BP_AICharacter_FireDisciple_W_HD2_Fighter_04_HPP
#define UE4SS_SDK_BP_AICharacter_FireDisciple_W_HD2_Fighter_04_HPP

class ABP_AICharacter_FireDisciple_W_HD2_Fighter_04_C : public ABP_FireDisciple_Base_W_C
{
};

#endif
