#ifndef UE4SS_SDK_BP_AICharacter_Grunt_M_HD2_Spectator_04_HPP
#define UE4SS_SDK_BP_AICharacter_Grunt_M_HD2_Spectator_04_HPP

class ABP_AICharacter_Grunt_M_HD2_Spectator_04_C : public ABP_Grunt_Base_C
{
};

#endif
