#ifndef UE4SS_SDK_BP_AiAction_WallJumpAttack_FireDisciple_HPP
#define UE4SS_SDK_BP_AiAction_WallJumpAttack_FireDisciple_HPP

class UBP_AiAction_WallJumpAttack_FireDisciple_C : public UBP_AiAction_WallJumpAttack_Vertical_C
{
};

#endif
