#ifndef UE4SS_SDK_BP_BigGuy_Miniboss_H2_ArchetypeDB_HPP
#define UE4SS_SDK_BP_BigGuy_Miniboss_H2_ArchetypeDB_HPP

class UBP_BigGuy_Miniboss_H2_ArchetypeDB_C : public UBP_BigGuy_Miniboss_ArchetypeDB_C
{
};

#endif
