#ifndef UE4SS_SDK_BP_DynamicAccessory_Grunt_M_Hat_01_HPP
#define UE4SS_SDK_BP_DynamicAccessory_Grunt_M_Hat_01_HPP

class ABP_DynamicAccessory_Grunt_M_Hat_01_C : public ABP_DynamicAccessory_Master_C
{
};

#endif
