#ifndef UE4SS_SDK_BP_DynamicAccessory_BigGuy_Sunglasses_01_HPP
#define UE4SS_SDK_BP_DynamicAccessory_BigGuy_Sunglasses_01_HPP

class ABP_DynamicAccessory_BigGuy_Sunglasses_01_C : public ABP_DynamicAccessory_Master_C
{
};

#endif
