#ifndef UE4SS_SDK_BP_DynamicAccessory_Grunt_M_Sunglasses_03_HPP
#define UE4SS_SDK_BP_DynamicAccessory_Grunt_M_Sunglasses_03_HPP

class ABP_DynamicAccessory_Grunt_M_Sunglasses_03_C : public ABP_DynamicAccessory_Master_C
{
};

#endif
