#ifndef UE4SS_SDK_BP_DynamicAccessory_Servant_M_Beanie_01_HPP
#define UE4SS_SDK_BP_DynamicAccessory_Servant_M_Beanie_01_HPP

class ABP_DynamicAccessory_Servant_M_Beanie_01_C : public ABP_DynamicAccessory_Master_C
{
};

#endif
