#ifndef UE4SS_SDK_BP_DynamicAccessory_BigGuy_Sunglasses_03_HPP
#define UE4SS_SDK_BP_DynamicAccessory_BigGuy_Sunglasses_03_HPP

class ABP_DynamicAccessory_BigGuy_Sunglasses_03_C : public ABP_DynamicAccessory_Master_C
{
};

#endif
