#ifndef UE4SS_SDK_BP_FireDisciple_NoAttack_DB_H2_Miniboss_HPP
#define UE4SS_SDK_BP_FireDisciple_NoAttack_DB_H2_Miniboss_HPP

class UBP_FireDisciple_NoAttack_DB_H2_Miniboss_C : public UBP_FireDisciple_NoAttack_DB_H2_C
{
};

#endif
