#ifndef UE4SS_SDK_BP_FidgetVariableWeightOrderService_HPP
#define UE4SS_SDK_BP_FidgetVariableWeightOrderService_HPP

class UBP_FidgetVariableWeightOrderService_C : public UFidgetVariableWeightOrderService
{
};

#endif
