#ifndef UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_YangPhase3_HPP
#define UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_YangPhase3_HPP

class UBP_FarMixerBlender_CombatLocked_Boss_YangPhase3_C : public UBP_FarMixerBlender_CombatLocked_Boss_Yang_C
{
};

#endif
