#ifndef UE4SS_SDK_BP_FlashKick_ArchetypeDB_H2_MiniBoss_HPP
#define UE4SS_SDK_BP_FlashKick_ArchetypeDB_H2_MiniBoss_HPP

class UBP_FlashKick_ArchetypeDB_H2_MiniBoss_C : public UBP_FlashKick_ArchetypeDB_H4_C
{
};

#endif
