#ifndef UE4SS_SDK_BP_FireDisciple_ArchetypeDB_MiniBoss_HPP
#define UE4SS_SDK_BP_FireDisciple_ArchetypeDB_MiniBoss_HPP

class UBP_FireDisciple_ArchetypeDB_MiniBoss_C : public UBP_FireDisciple_ArchetypeDB_H2_C
{
};

#endif
