#ifndef UE4SS_SDK_BP_FlashKick_ArchetypeDB_DanceFloor_AllTraversalAllowed_HPP
#define UE4SS_SDK_BP_FlashKick_ArchetypeDB_DanceFloor_AllTraversalAllowed_HPP

class UBP_FlashKick_ArchetypeDB_DanceFloor_AllTraversalAllowed_C : public UBP_FlashKick_ArchetypeDB_H2_C
{
};

#endif
