#ifndef UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_Yang_HPP
#define UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_Yang_HPP

class UBP_FarMixerBlender_CombatLocked_Boss_Yang_C : public UBP_FarMixerBlender_CombatLocked_Boss_C
{
};

#endif
