#ifndef UE4SS_SDK_BP_FireDisciple_NoAttack_DB_H2_Base_HPP
#define UE4SS_SDK_BP_FireDisciple_NoAttack_DB_H2_Base_HPP

class UBP_FireDisciple_NoAttack_DB_H2_Base_C : public UBP_FireDisciple_NoAttack_DB_H2_C
{
};

#endif
