#ifndef UE4SS_SDK_BP_FireDisciple_ArchetypeDB_MiniBoss_H2_HPP
#define UE4SS_SDK_BP_FireDisciple_ArchetypeDB_MiniBoss_H2_HPP

class UBP_FireDisciple_ArchetypeDB_MiniBoss_H2_C : public UBP_FireDisciple_ArchetypeDB_MiniBoss_C
{
};

#endif
