#ifndef UE4SS_SDK_BP_Grunt_LastManSynchronizedAttacksHitAction_HPP
#define UE4SS_SDK_BP_Grunt_LastManSynchronizedAttacksHitAction_HPP

class UBP_Grunt_LastManSynchronizedAttacksHitAction_C : public UBP_LastManSynchronizedAttacksHitAction_C
{
};

#endif
