#ifndef UE4SS_SDK_BP_HitboxCondition_DifficultyIsNormal_HPP
#define UE4SS_SDK_BP_HitboxCondition_DifficultyIsNormal_HPP

class UBP_HitboxCondition_DifficultyIsNormal_C : public UHitBoxGenericCondition
{
};

#endif
