#ifndef UE4SS_SDK_BP_HitboxCondition_DifficultyIsNotEasy_HPP
#define UE4SS_SDK_BP_HitboxCondition_DifficultyIsNotEasy_HPP

class UBP_HitboxCondition_DifficultyIsNotEasy_C : public UHitBoxGenericCondition
{
};

#endif
