#ifndef UE4SS_SDK_BP_HitboxCondition_DifficultyIsNotHard_HPP
#define UE4SS_SDK_BP_HitboxCondition_DifficultyIsNotHard_HPP

class UBP_HitboxCondition_DifficultyIsNotHard_C : public UHitBoxGenericCondition
{
};

#endif
