#ifndef UE4SS_SDK_BP_IsTargetKnockedDownComboCondition_HPP
#define UE4SS_SDK_BP_IsTargetKnockedDownComboCondition_HPP

class UBP_IsTargetKnockedDownComboCondition_C : public UComboAIConditionIsTargetFightingState
{
};

#endif
