#ifndef UE4SS_SDK_BP_LessonDummy_Archetype_SpecialAttacks_02_HPP
#define UE4SS_SDK_BP_LessonDummy_Archetype_SpecialAttacks_02_HPP

class UBP_LessonDummy_Archetype_SpecialAttacks_02_C : public UBP_LessonDummy_Archetype_Master_C
{
};

#endif
