#ifndef UE4SS_SDK_BP_Menu_Debug_HPP
#define UE4SS_SDK_BP_Menu_Debug_HPP

class UBP_Menu_Debug_C : public UDebugMenu
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* ErrorMessage;
    class USCButton* ActivatePerf;
    class USCButton* AllCheats_Button;
    class USCButton* AutoTakedown;
    class UBP_Btn_DebugTeleport_C* BP_Btn_Debug;
    class UBP_Btn_DebugForceTakeDown_C* BP_DebugForceTakeDownButton;
    class USCButton* Button_235;
    class USCButton* Button_Add_CheatsUnlockPoint;
    class USCButton* Button_AI;
    class USCButton* Button_FillFocus;
    class USCButton* Button_Focus_Off;
    class USCButton* Button_Focus_On;
    class USCButton* Button_GenderSwap;
    class USCButton* Button_HideDeathMenu;
    class USCButton* Button_HideDebugDisplay;
    class USCButton* Button_HideHUD;
    class USCButton* Button_Load_Backup;
    class USCButton* Button_LockAllAbilities_1;
    class USCButton* Button_LockGoals;
    class USCButton* Button_Multiplier_Add01;
    class USCButton* Button_Multiplier_Add1;
    class USCButton* Button_Multiplier_Reset;
    class USCButton* Button_Multiplier_Reset_2;
    class USCButton* Button_Reset_Save_Global;
    class USCButton* Button_Reset_Save_Option;
    class USCButton* Button_Reset_Save_Run;
    class USCButton* Button_ResetDetectiveBoard;
    class USCButton* Button_ResetDiminishing;
    class UTextBlock* Button_ResetDiminishing_Text;
    class USCButton* Button_Save;
    class USCButton* Button_Save_Backup;
    class USCButton* Button_Score_Add;
    class USCButton* Button_Score_Reset;
    class USCButton* Button_ScoringV2_Base;
    class USCButton* Button_ScoringV2_Boss;
    class USCButton* Button_ScoringV2_Nervous;
    class USCButton* Button_SpawnWeapon;
    class USCButton* Button_SpectatorMode;
    class USCButton* Button_UnlockAllAbilities_1;
    class USCButton* Button_UnlockAllDetectiveBoard;
    class USCButton* Button_UnlockFocus;
    class USCButton* Button_UnlockGoals;
    class USCButton* ButtonTrailerH1;
    class USCButton* ButtonTrailerWuguan;
    class USCButton* Change_Language_En;
    class USCButton* Change_Language_Zh;
    class UEditableTextBox* CharaName;
    class UCanvasPanel* confirm_reset;
    class USCButton* CreateProfile;
    class UVerticalBox* DebugButtonsContainer;
    class USCButton* DebugInputs;
    class USCButton* DecreaseAge;
    class USCButton* DecreaseCharges;
    class USCButton* DecreaseDT_Button;
    class USCButton* DifficultyButton;
    class UTextBlock* DifficultyText;
    class USCButton* DisplayCheats;
    class USCButton* DisplayCredits;
    class UEditableTextBox* EditAge;
    class UEditableTextBox* EditDeathCount;
    class USCButton* ForceTakedown;
    class UScrollBox* ForceTakedownScrollBox;
    class UTextBlock* GenderSwap;
    class USCButton* Ghost_Off;
    class USCButton* Ghost_On;
    class UTextBlock* HIdeDeathMenu_Text;
    class UTextBlock* HIdeHUDText;
    class UTextBlock* HIdeHUDText_1;
    class USCButton* IncreaseAge;
    class USCButton* IncreaseCharges;
    class USCButton* IncreaseDT_Button;
    class UInvalidationBox* InvalidationBox_0;
    class USCButton* Invincible_Off;
    class USCButton* Invincible_On;
    class USCButton* KillAllAis;
    class USCButton* LevelTeleports;
    class USCButton* LoadButton;
    class UCanvasPanel* MenuList;
    class USCButton* OnePunchMan;
    class USCButton* Play;
    class USCButton* ResetAge;
    class USCButton* ResetCharges;
    class USCButton* ResetStatsButton;
    class UScrollBox* Saves_Box;
    class USCButton* SCButton_10000XP;
    class USCButton* SCButton_1000XP;
    class USCButton* SCButton_100XP;
    class USCButton* SCButton_No;
    class USCButton* SCButton_Yes;
    class UScrollBox* ScrollBox_DebugButtons;
    class USCButton* SetAge;
    class USCButton* SetCharges;
    class USCButton* SloMoDisable;
    class USCButton* SloMoDisable_1;
    class USCButton* SlomoMode;
    class UTextBlock* SlomoMode_Text;
    class UTextBlock* SlowMoDisable_Text;
    class UTextBlock* SlowMoDisable_Text_1;
    class USCButton* StartStopRecording;
    class UTextBlock* StartStopRecordText;
    class USCButton* Structure_Off;
    class USCButton* Structure_On;
    class UVerticalBox* TakedownContainer;
    class UTextBlock* Text_ErrorMessage;
    class UTextBlock* TextBlock_GlobalXP;
    class USCButton* TimeDilation;
    class USCButton* ToggleTagDebug;
    class UVerticalBox* VerticalBox_56;
    class UWBP_ControllerDebug_C* ControllerDebug;
    class UCapsuleComponent* PlayerHitCapsule;
    TSubclassOf<class UBP_WallTakedownAnimRequest_C> TakedownWallRequest;
    TSubclassOf<class UBP_BaseTakedownAnimRequest_C> TakedownRequest;
    TArray<FTakedownDebugAnim> TakedownAnims;
    class ABP_DebugTeleportManager_C* Level_DebugTeleportManager;
    TArray<class AActor*> DestinationActors;
    class UWBP_TimeDilationDebug_C* TimeDilationDebug;
    class UWBP_DebugCheatList_C* DebugCheatListWidget;
    bool IsEditingTimeDilation;
    FVector Player Pos Before Debug Sequence;
    int32 Last Played Sequence Index;
    FName Selected Debug Sequences;
    TArray<class ULevelSequence*> Trailer Wuguan Sequences;
    TArray<class ULevelSequence*> Trailer H1 Sequences;
    class UDetectiveTagsDebugguer_C* DetectiveTagsDebugguer;
    TArray<class TSubclassOf<ABPWeapon_C>> SpawningWeapons;
    float GenderSwapPressedGameTime;
    class UBPStatsComponent_MainChar_C* FightingCharacterStatsComponentBP;
    class UBP_PlayerScoringComponent_C* PlayerScoringComponent;

    FText Get_DifficultyText_Text_0();
    FText Get_HIdeDeathMenu_Text();
    void Get Debug Sequences(TArray<class ULevelSequence*>& Sequences);
    void Teleport Player To Saved Location Before Sequence();
    void Save Player Location Before Sequence();
    class ALevelSequenceActor* Play Sequence(int32 Index);
    class UBP_Btn_DebugTeleport_C* Add Debug ScrollBox Button(const FAdd Debug ScrollBox ButtonOn Pressed& On Pressed);
    void Display Debug Scrollbox(bool Clear  content);
    void RefreshEditModeDisplay();
    void RefreshDilationOverrideDisplay();
    void RefreshReplayDisplay();
    void InitCheatList();
    FText GetGenderSwapText();
    FText GetFocusText();
    void SetAgeFromTextInput();
    void SetLivesFromTextInput();
    class UStatsComponent* GetStatsComponent();
    FText GetAgeText();
    void FetchStatsValues();
    FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    bool GetbIsEnabled_OpenSpend();
    ESlateVisibility Get_SpendPointsVisibility();
    FText GetText_GlobalLevel();
    FText GetText_GlobalXP();
    void AddGlobalXP(int32 XPAmount);
    void InitDistributionPoints();
    void OnFail_BD4089354637E5113882DA8405152F53();
    void OnSuccess_BD4089354637E5113882DA8405152F53();
    void CultureSwitchFailed_8740231D4F5470AC42FECEA8CBC9AC42();
    void CultureSwitched_8740231D4F5470AC42FECEA8CBC9AC42();
    void CultureSwitchFailed_0581726E4AAEB841959EDDB1CD020E79();
    void CultureSwitched_0581726E4AAEB841959EDDB1CD020E79();
    void Construct();
    void BndEvt__Button03_K2Node_ComponentBoundEvent_63_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Invicible_K2Node_ComponentBoundEvent_103_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_SpectatorMode_K2Node_ComponentBoundEvent_199_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Invincible_Off_K2Node_ComponentBoundEvent_5548_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Guard_On_K2Node_ComponentBoundEvent_2000_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Guard_Off_K2Node_ComponentBoundEvent_2071_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Save_K2Node_ComponentBoundEvent_3237_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_1_K2Node_ComponentBoundEvent_4732_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_5_K2Node_ComponentBoundEvent_5076_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_1000XP_K2Node_ComponentBoundEvent_6943_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CharaName_K2Node_ComponentBoundEvent_531_OnEditableTextBoxCommittedEvent__DelegateSignature(const FText& Text, TEnumAsByte<ETextCommit::Type> CommitMethod);
    void BndEvt__SCButton_63_K2Node_ComponentBoundEvent_708_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_No_K2Node_ComponentBoundEvent_2915_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_Yes_K2Node_ComponentBoundEvent_3005_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ResetStatsButton_K2Node_ComponentBoundEvent_845_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ActivatePerf_K2Node_ComponentBoundEvent_1149_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__AllCheats_Button_K2Node_ComponentBoundEvent_2708_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_5_K2Node_ComponentBoundEvent_623_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SCButton_2_K2Node_ComponentBoundEvent_620_OnButtonClickedEvent__DelegateSignature();
    void AddControllerDebugToviewport();
    void BndEvt__SCButton_2_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature();
    void ActivateCapsuleCollision(bool Activate);
    void BndEvt__BtSetCharacterAge_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BtSetLives_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BtResetAge_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BtLives-_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BtLives+_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BtAge-_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BtAge+_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_DebugMode_1_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
    void OnFocusReceived_Event_0(class USCButton* _buttonFocused);
    void BndEvt__Button_Focus_On_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Focus_Off_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__LevelTeleports_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void ButtonPressed(int32 ID);
    void BndEvt__CreateProfile_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__KillAllAis_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__DecreaseDT_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__IncreaseDT_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature();
    void DisplayTimeDilation();
    void BndEvt__TimeDilation_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Reset_Save_Option_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Reset_Save_Run_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Reset_Save_Global_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ONEPUNCHMAN_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Play_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__StartStopRecording_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_ResetDetectiveBoard_K2Node_ComponentBoundEvent_29_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_UnlockAllDetectiveBoard_K2Node_ComponentBoundEvent_30_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Save_Backup_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Load_Backup_K2Node_ComponentBoundEvent_31_OnButtonClickedEvent__DelegateSignature();
    void onTextCommitedBackUp(const FText& Text, TEnumAsByte<ETextCommit::Type> CommitMethod);
    void button clicked(class UBP_Button_LoadSave_C* Button);
    void OnOverrideBackup(class UBP_Button_LoadSave_C* Button);
    void Delete Backup(class UBP_Button_LoadSave_C* Button);
    void BndEvt__SloMoDisable_K2Node_ComponentBoundEvent_32_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SlomoMode_K2Node_ComponentBoundEvent_35_OnButtonClickedEvent__DelegateSignature();
    void DecreaseDT();
    void IncreaseDT();
    void BndEvt__Button_235_K2Node_ComponentBoundEvent_33_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_AI_K2Node_ComponentBoundEvent_34_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ButtonSequences_K2Node_ComponentBoundEvent_36_OnButtonClickedEvent__DelegateSignature();
    void On Chose Sequence To Play(int32 ID);
    void On Focus Debug ScrollBox(class USCButton* _buttonFocused);
    void On Finished Debug Sequence();
    void On Chose Play All Sequences(int32 ID);
    void On Finished One Sequence();
    void BndEvt__ButtonTrailerH1_K2Node_ComponentBoundEvent_37_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ToggleTagDebug_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_SloMoDisable_1_K2Node_ComponentBoundEvent_39_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_HideDeathMenu_K2Node_ComponentBoundEvent_40_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_ONEPUNCHMAN_1_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_SpawnWeapon_K2Node_ComponentBoundEvent_43_OnButtonClickedEvent__DelegateSignature();
    void OnPressedSpawnWeapon(int32 ID);
    void BndEvt__BP_Menu_Debug_Button_GenderSwap_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_GenderSwap_K2Node_ComponentBoundEvent_42_OnButtonReleasedEvent__DelegateSignature();
    void LaunchGenderSwap();
    void BndEvt__BP_Menu_Debug_Button_UnlockAllAbilities_1_K2Node_ComponentBoundEvent_24_OnButtonPressedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_LockAllAbilities_1_K2Node_ComponentBoundEvent_44_OnButtonPressedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Multiplier_Add01_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Multiplier_Add1_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Multiplier_Reset_K2Node_ComponentBoundEvent_47_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_HideDebugDisplay_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_UnlockFocus_K2Node_ComponentBoundEvent_48_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_FillFocus_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Multiplier_Add01_1_K2Node_ComponentBoundEvent_50_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Multiplier_Reset_1_K2Node_ComponentBoundEvent_51_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_DisplayCredits_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Change_Language_Zh_K2Node_ComponentBoundEvent_53_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Change_Language_En_K2Node_ComponentBoundEvent_54_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_DisplayCheats_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature();
    void OnVisibilityChanged_Event_0(ESlateVisibility InVisibility);
    void BndEvt__BP_Menu_Debug_DifficultyButton_K2Node_ComponentBoundEvent_55_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Add_CheatsUnlockPoint_K2Node_ComponentBoundEvent_57_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_Multiplier_Reset_2_K2Node_ComponentBoundEvent_58_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_ScoringV2_Toggle_K2Node_ComponentBoundEvent_59_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_ScoringV2_Base_K2Node_ComponentBoundEvent_60_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_ScoringV2_Nervous_K2Node_ComponentBoundEvent_61_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_ScoringV2_Boss_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_LockGoals_K2Node_ComponentBoundEvent_56_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__BP_Menu_Debug_Button_UnlockGoals_K2Node_ComponentBoundEvent_63_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_BP_Menu_Debug(int32 EntryPoint);
};

#endif
