#ifndef UE4SS_SDK_BP_Menu_Options_Cheat_HPP
#define UE4SS_SDK_BP_Menu_Options_Cheat_HPP

class UBP_Menu_Options_Cheat_C : public UGameplayOptionsMenu
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* InsuficientCurrency;
    class UWidgetAnimation* CheatBoughtFeedback;
    class UBP_Btn_SpinBox_Modifiers_C* AttackSpeed;
    class UBP_Btn_SpinBox_Modifiers_C* Autothrow;
    class UImage* BlackTransparentBG;
    class UHorizontalBox* Border_InputsnoAnim;
    class UBP_Menu_Popup_Validation_C* BP_Menu_Popup_Validation;
    class UBP_Menu_Popup_Validation_C* BP_Menu_Popup_Validation_Reset;
    class UBP_Notif_Spend_C* BP_Notif_Spend;
    class UBP_Btn_SpinBox_Modifiers_C* BuildUpMult;
    class UBP_Btn_SpinBox_Modifiers_C* BulletTime;
    class UBP_Btn_SpinBox_Modifiers_C* BulletTime_Choice;
    class UBP_Btn_CheatCategory_Tab_C* Cat_Ennemies;
    class UBP_Btn_CheatCategory_Tab_C* Cat_Various;
    class UBP_Btn_CheatCategory_Tab_C* Cat_YourCharacter;
    class UVerticalBox* Category_Ennemies;
    class UVerticalBox* Category_EnnemiesStudentOnly;
    class UVerticalBox* Category_Various;
    class UVerticalBox* Category_YourCharacter;
    class UImage* CurrencyIcon;
    class UBP_Btn_SpinBox_Modifiers_C* EnnemyLevel;
    class UBP_Btn_SpinBox_Modifiers_C* EnnemyLevels;
    class UTextBlock* FocusUpdatedText;
    class UBP_Btn_SpinBox_Modifiers_C* Guardignored;
    class UBP_Btn_SpinBox_Modifiers_C* HealthManagement;
    class UBP_Btn_SpinBox_Modifiers_C* InfiniteFocus;
    class UBP_Btn_SpinBox_Modifiers_C* InfiniteStructure;
    class UBP_Btn_InputTip_C* InputTip_Activate;
    class UBP_Btn_InputTip_C* InputTip_Back;
    class UBP_Btn_InputTip_C* InputTip_Default;
    class UBP_Btn_InputTip_C* InputTip_Unlock;
    class UBP_Btn_SpinBox_Modifiers_C* LowGravity;
    class UBP_Btn_SpinBox_Modifiers_C* MCAge;
    class UBP_Btn_SpinBox_Modifiers_C* MCAge_Choice;
    class UBP_Btn_SpinBox_Modifiers_C* MCDoubleDamageReveived;
    class UBP_Btn_SpinBox_Modifiers_C* MCHealth;
    class UBP_Btn_SpinBox_Modifiers_C* NoDeathCounterDecrement;
    class UBP_Btn_SpinBox_Modifiers_C* NoEnvironmentalWeapon;
    class UBorder* NotEoughCurrenyPanel;
    class UBP_Btn_SpinBox_Modifiers_C* OnePunchMan;
    class UBP_Btn_SpinBox_Modifiers_C* Pendant;
    class UCanvasPanel* Popup;
    class UCanvasPanel* Popup_ConfirmReset;
    class UScrollBox* ScrollBox_Ennemies;
    class UScrollBox* ScrollBox_EnnemiesStudentOnly;
    class UScrollBox* ScrollBox_Various;
    class UScrollBox* ScrollBox_YourCharacter;
    class UBP_Btn_SpinBox_Modifiers_C* Shrine;
    class UBP_Btn_SpinBox_Modifiers_C* Skills;
    class UBP_Btn_SpinBox_Modifiers_C* StructureBreakingDeflect;
    class UWidgetSwitcher* SwitcherCheats;
    class UBP_Btn_SpinBox_Modifiers_C* UnbreakableWeapon;
    class UBP_Btn_SpinBox_Modifiers_C* Vampire;
    class UBP_Btn_SpinBox_Modifiers_C* VampireStudent;
    class UVerticalBox* VBCategories;
    class UImage* WhiteMask;
    class UButtonUserWidget* FocusedCombo;
    bool AudioApplied;
    class UBP_Btn_SpinBox_C* FocusedOption;
    TMap<class FString, class FText> AudioLanguageMap;
    bool IsFocusScrollBar;
    TArray<class UWidget*> AllCheats;
    class UBP_Btn_SpinBox_Modifiers_C* SpinboxToUnlock;
    FBP_Menu_Options_Cheat_COnPopupVisibilityChanged OnPopupVisibilityChanged;
    void OnPopupVisibilityChanged(bool Visible);
    FBP_Menu_Options_Cheat_CAnyCheatStateUpdated AnyCheatStateUpdated;
    void AnyCheatStateUpdated();
    bool UnifinishedStudentRunMode;
    bool IsFocusedButtonCheckbox;
    bool bDebugMode;

    void ShowHideBulletTimeButtons();
    void OnUpdateModeChange();
    void AllowCategoryNavigation();
    void IsUnfinishedStudentRun(bool& IsUnifinishedStudentRun);
    void SetDebugMode();
    void UpdatePrimaryInputTip(class UBP_Btn_SpinBox_Modifiers_C* Btn);
    void Set NavigationRulesToCategories();
    class UWidget* LoopFromBottomCategory(EUINavigation Navigation);
    class UWidget* LoopFromTopCategory(EUINavigation Navigation);
    void ResetAllButtonsIndex(bool& HasAnybuttonBeenUpdated);
    bool BPE_OnMenuActionSecondaryPressed();
    void SetupAllButtonsDetails();
    class UWidget* LoopFromBottom(EUINavigation Navigation);
    class UWidget* LoopFromTop(EUINavigation Navigation);
    void ScrollToTop();
    void RefreshButtons();
    void OnLockedSpinboxClicked(class UBP_Btn_SpinBox_Modifiers_C* SpinboxModifier);
    void NoPopup();
    void YesPopupResetDefault();
    void YesPopup();
    void ResetCategoriesState();
    void FocusOnCategoryAtIndex(int32 Index);
    void Focus on First Element(class UWidget* ParentCategory);
    void UpdateUnlockPointsAvailable();
    void UpdateActivatedCheatsSumary();
    void UpdateCheatActivationOnValueChanged(float RatioFloat, FGameplayTag GameplayTag);
    bool BPE_OnBackButtonPressed();
    void LoopCheatOptions(bool SetDefault);
    void LaunchBackSequence();
    void Construct();
    void BPE_GiveFocus();
    void BPE_OnMenuTransitionOut(EMenuTransitions _eTransition, EMenuEnum _eNewMenu);
    void BPE_OnMenuTransitionIn(EMenuTransitions _eTransition, EMenuEnum _ePrevMenu);
    void OnUnlocked_Event();
    void OnValueChanged_Event(int32 Value, ECycleDirection Direction, float RatioFloat, FGameplayTag CheatGameplayTag, class UBP_Btn_SpinBox_Modifiers_C* Btn);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Various_K2Node_ComponentBoundEvent_1_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Cheat_Cat_YourCharacter_K2Node_ComponentBoundEvent_3_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Ennemies_K2Node_ComponentBoundEvent_5_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Various_K2Node_ComponentBoundEvent_0_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_YourCharacter_K2Node_ComponentBoundEvent_2_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Ennemies_K2Node_ComponentBoundEvent_4_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_YourCharacter_K2Node_ComponentBoundEvent_6_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Ennemies_K2Node_ComponentBoundEvent_7_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Various_K2Node_ComponentBoundEvent_8_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BPE_OnUIInputModeChanged(EUIInputModes _eMode, bool _bInit);
    void ExecuteUbergraph_BP_Menu_Options_Cheat(int32 EntryPoint);
    void OnPopupVisibilityChanged__DelegateSignature(bool Visible);
    void AnyCheatStateUpdated__DelegateSignature();
};

#endif
