#ifndef UE4SS_SDK_BP_PushTraversalInstigatorCheckTargetOrderService_HPP
#define UE4SS_SDK_BP_PushTraversalInstigatorCheckTargetOrderService_HPP

class UBP_PushTraversalInstigatorCheckTargetOrderService_C : public UCheckTargetStateOrderService
{
};

#endif
