#ifndef UE4SS_SDK_BP_RedirectToTargetRagingBullService_Entry_HPP
#define UE4SS_SDK_BP_RedirectToTargetRagingBullService_Entry_HPP

class UBP_RedirectToTargetRagingBullService_Entry_C : public URedirectToTargetOrderService
{
};

#endif
