#ifndef UE4SS_SDK_BP_ShrineModifierCalculation_HealthTakedown_HPP
#define UE4SS_SDK_BP_ShrineModifierCalculation_HealthTakedown_HPP

class UBP_ShrineModifierCalculation_HealthTakedown_C : public UBP_ShrineModifierCalculation_C
{
};

#endif
