#ifndef UE4SS_SDK_BP_Servant_ArchetypeDB_Stronger_H2_HPP
#define UE4SS_SDK_BP_Servant_ArchetypeDB_Stronger_H2_HPP

class UBP_Servant_ArchetypeDB_Stronger_H2_C : public UBP_Grunt_ArchetypeDB_Base_C
{
};

#endif
