#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_AvoidGain_Lvl1_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_AvoidGain_Lvl1_HPP

class UBP_ShrineGameplayEffect_AvoidGain_Lvl1_C : public USCGameplayEffect
{
};

#endif
