#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_WeaponImpact_Lv3_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_WeaponImpact_Lv3_HPP

class UBP_ShrineGameplayEffect_WeaponImpact_Lv3_C : public UBP_ShrineGameplayEffect_WeaponImpact_Lv1_C
{
};

#endif
