#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_ParryImpact_Lvl2_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_ParryImpact_Lvl2_HPP

class UBP_ShrineGameplayEffect_ParryImpact_Lvl2_C : public UBP_ShrineGameplayEffect_ParryImpact_Lvl1_C
{
};

#endif
