#ifndef UE4SS_SDK_BP_SeanTransition_Death_Takedown_HPP
#define UE4SS_SDK_BP_SeanTransition_Death_Takedown_HPP

class UBP_SeanTransition_Death_Takedown_C : public UBP_BossTransitionSyncAttackHit_C
{
};

#endif
