#ifndef UE4SS_SDK_BP_ThrowObjectAnimRequest_BatFamily_HPP
#define UE4SS_SDK_BP_ThrowObjectAnimRequest_BatFamily_HPP

class UBP_ThrowObjectAnimRequest_BatFamily_C : public UBP_ThrowObjectAnimRequest_C
{
};

#endif
