#ifndef UE4SS_SDK_BP_ThrowableData_Weapon_BatFamily_HPP
#define UE4SS_SDK_BP_ThrowableData_Weapon_BatFamily_HPP

class UBP_ThrowableData_Weapon_BatFamily_C : public UBP_ThrowableData_WeaponMaster_C
{
};

#endif
