#ifndef UE4SS_SDK_BP_ThrowableData_Throwable_OneHandedFamily_HPP
#define UE4SS_SDK_BP_ThrowableData_Throwable_OneHandedFamily_HPP

class UBP_ThrowableData_Throwable_OneHandedFamily_C : public UBP_ThrowableData_ThrowableMaster_C
{
};

#endif
