#ifndef UE4SS_SDK_BP_ThrowableData_Weapon_BladeFamily_Kodachi_HPP
#define UE4SS_SDK_BP_ThrowableData_Weapon_BladeFamily_Kodachi_HPP

class UBP_ThrowableData_Weapon_BladeFamily_Kodachi_C : public UBP_ThrowableData_Weapon_BladeFamily_C
{
};

#endif
