#ifndef UE4SS_SDK_BP_TE_BackFrontLightDirectionalWeightEval_HPP
#define UE4SS_SDK_BP_TE_BackFrontLightDirectionalWeightEval_HPP

class UBP_TE_BackFrontLightDirectionalWeightEval_C : public UTE_DirectionalWeightEvaluation
{
};

#endif
