#ifndef UE4SS_SDK_BP_Unbreakable_WeaponGameplayData_Blades_HPP
#define UE4SS_SDK_BP_Unbreakable_WeaponGameplayData_Blades_HPP

class UBP_Unbreakable_WeaponGameplayData_Blades_C : public UBP_WeaponGameplayData_BladesFamily_C
{
};

#endif
