#ifndef UE4SS_SDK_BP_Unbreakable_WeaponGameplayData_Bat_HPP
#define UE4SS_SDK_BP_Unbreakable_WeaponGameplayData_Bat_HPP

class UBP_Unbreakable_WeaponGameplayData_Bat_C : public UBP_WeaponGameplayData_BatFamily_C
{
};

#endif
