#ifndef UE4SS_SDK_BP_WallEnvironementalTakedownSettings_HPP
#define UE4SS_SDK_BP_WallEnvironementalTakedownSettings_HPP

class UBP_WallEnvironementalTakedownSettings_C : public UWallEnvironmentalAttackSettings
{
};

#endif
