#ifndef UE4SS_SDK_BP_Weapon_MCStaff_ThrowObjectAnimRequest_HPP
#define UE4SS_SDK_BP_Weapon_MCStaff_ThrowObjectAnimRequest_HPP

class UBP_Weapon_MCStaff_ThrowObjectAnimRequest_C : public UBP_ThrowObjectAnimRequest_C
{
};

#endif
