#ifndef UE4SS_SDK_BP_WeaponData_Staff_FireDisciple_H4_HPP
#define UE4SS_SDK_BP_WeaponData_Staff_FireDisciple_H4_HPP

class UBP_WeaponData_Staff_FireDisciple_H4_C : public UBP_WeaponData_Staff_FireDisciple_C
{
};

#endif
