#ifndef UE4SS_SDK_DetectiveBoardItem_HPP
#define UE4SS_SDK_DetectiveBoardItem_HPP

class UDetectiveBoardItem_C : public UDetectiveLinkableItem_C
{
    class UWidgetAnimation* LoadedAnim;
    class UWidgetAnimation* ZoomFocusAnim;
    class UWidgetAnimation* NotifAnim;
    class UWidgetAnimation* FocusAnim;
    class UCanvasPanel* CanvasPanel_0;
    class UDetectiveBlocker_C* DetectiveBlocker;
    class UDetectiveKey_C* DetectiveKey;
    class UImage* InvestigationImage;
    class USCButton* ItemButton;
    class UImage* ItemImage;
    class USizeBox* MainSizeBox;
    class UOverlay* Notif;
    class UImage* SelectionOutlineLocked;
    class UImage* SelectionOutlineUnlocked;
    class UWidgetSwitcher* StateSwitcher;
    class UBorder* Unlocked;
    TSoftObjectPtr<UTexture2D> Image;
    TSoftObjectPtr<UTexture2D> LowResImage;
    class UDetectiveBoardEntryList_C* EntryListWidgetOverride;
    FDetectiveBoardItem_CItemHovered ItemHovered;
    void ItemHovered(class UDetectiveBoardItem_C* bpp__Item__pf, bool bpp__bByMouse__pf);
    FDetectiveBoardItem_CItemUnhovered ItemUnhovered;
    void ItemUnhovered(class UDetectiveBoardItem_C* bpp__Item__pf);
    bool Rendered;
    FDetectiveBoardItem_CItemClicked itemClicked;
    void ItemClicked(class UDetectiveBoardItem_C* bpp__Item__pf);
    TSoftObjectPtr<UTexture2D> LowResImageToShow;
    TSoftObjectPtr<UTexture2D> ImageToShow;
    DetectiveBoardItemSFXTypes SFXType;
    bool bBlockHoverCall;
    FVector2D LinkOffset;
    bool bUseLowResImage;
    float ItemDefaultSize;
    bool bForceNotifHidden;
    bool IsZoomedItem;
    FVector2D WantedSlotGridSize;
    int32 NewVar_0;
    bool Temp_bool_Variable;
    ESlateVisibility Temp_byte_Variable;
    ESlateVisibility Temp_byte_Variable_1;
    class UObject* K2Node_CustomEvent_Loaded;
    ESlateVisibility K2Node_Select_Default;
    class UObject* Temp_object_Variable;
    class UTexture2D* K2Node_DynamicCast_AsTexture_2D;
    bool K2Node_DynamicCast_bSuccess;
    FAnchors K2Node_MakeStruct_Anchors;
    bool Temp_bool_Variable_1;
    class USCButton* K2Node_ComponentBoundEvent__buttonFocused;
    class USCButton* K2Node_ComponentBoundEvent__buttonUnfocused;
    class UWidgetAnimation* K2Node_Select_Default_1;
    bool Temp_bool_Variable_2;
    bool K2Node_CustomEvent_bPlayAnimation;
    FDetectiveBoardItem_CK2Node_CreateDelegate_OutputDelegate K2Node_CreateDelegate_OutputDelegate;
    void OnAssetLoaded(class UObject* Loaded);
    float CallFunc_BreakVector2D_X;
    float CallFunc_BreakVector2D_Y;
    bool Temp_bool_Variable_3;
    TSoftObjectPtr<UTexture2D> K2Node_Select_Default_2;
    float K2Node_Select_Default_3;
    class UTexture2D* K2Node_DynamicCast_AsTexture_2D_1;
    bool K2Node_DynamicCast_bSuccess_1;

    void ItemUnhovered__DelegateSignature(class UDetectiveBoardItem_C* bpp__Item__pf);
    void ItemHovered__DelegateSignature(class UDetectiveBoardItem_C* bpp__Item__pf, bool bpp__bByMouse__pf);
    void ItemClicked__DelegateSignature(class UDetectiveBoardItem_C* bpp__Item__pf);
    void UpdateVisual();
    void UpdateTypeImages(class UAbilitySystemComponent* bpp__InComponent__pf, bool bpp__Editor__pf);
    void UpdateItems(bool bpp__Editor__pf);
    void UpdateImageAlignment();
    void TryToShowEntries();
    void TryToHideEntries();
    bool ShouldShowEntries();
    void SetSlotGridSize(int32 bpp__Row__pf, int32 bpp__Column__pf);
    void OnLoaded_8C86884B473BD2A666D440A16CDD0120(class UObject* bpp__Loaded__pf);
    void OnItemImageLoadStarted();
    void OnItemImageLoaded(bool bpp__bPlayAnimation__pf);
    FEventReply OnFocusReceived(FGeometry bpp__MyGeometry__pf, FFocusEvent bpp__InFocusEvent__pf);
    void HideEntries();
    class UDetectiveBoardEntryList_C* GetEntryListWidget();
    void GetAnchorOverride(class UWidget*& bpp__OutResultValue__pf, FVector2D& bpp__OutOffset__pf);
    void ForceSwitcherInvalidation();
    void ExecuteUbergraph_DetectiveBoardItem_3(int32 bpp__EntryPoint__pf);
    void DismissAllNotifies(bool bpp__bUpdateVisibility__pf);
    void Construct();
    void ClearImage();
    void BPE_OnSynchronizeProperties();
    void BndEvt__SCButton_0_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_4_ButtonUnFocused__DelegateSignature(class USCButton* bpp___buttonUnfocused__pf);
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_3_ButtonFocused__DelegateSignature(class USCButton* bpp___buttonFocused__pf);
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
};

#endif
