#ifndef UE4SS_SDK_DodgeRushRecoveryAvailabilityOrderService_HPP
#define UE4SS_SDK_DodgeRushRecoveryAvailabilityOrderService_HPP

class UDodgeRushRecoveryAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
