#ifndef UE4SS_SDK_DodgeAndAvoidAvailabilityOrderService_HPP
#define UE4SS_SDK_DodgeAndAvoidAvailabilityOrderService_HPP

class UDodgeAndAvoidAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
