#ifndef UE4SS_SDK_GenericAllAvailabilityOrderService_HPP
#define UE4SS_SDK_GenericAllAvailabilityOrderService_HPP

class UGenericAllAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
