#ifndef UE4SS_SDK_Hideout_2_LD_HPP
#define UE4SS_SDK_Hideout_2_LD_HPP

class AHideout_2_LD_C : public AThePlainesLevel
{
    FPointerToUberGraphFrame UberGraphFrame;
    bool Situation ResolvedSideRoom2 ;
    bool Situation Resolved SideRoom 1;
    TArray<class AActor*> TeleportSpot;
    int32 TeleportTarget;
    bool Up;
    bool OnDanceFloor;
    class AActor* HostTriggerAlert;
    TSoftObjectPtr<AActor> LightSwitch_01;
    TSoftObjectPtr<AActor> LightSwitch_03;
    TSoftObjectPtr<AActor> LightSwitch_Pitt_01;
    TSoftObjectPtr<AActor> CorridorLightFlick_01;
    bool RefillHasBeenDone;
    bool FlashkickHasBeenTrigger;
    bool DeadBar;
    bool 100_SecondFireDiscipleDown;
    TSoftObjectPtr<AActor> AudioSwitch 02;
    TSoftObjectPtr<AActor> AudioSwitch 03;
    FName DanceFloor Alert Threshold Name;
    TArray<class ABP_AiSpawnerGroup_C*> SpawnerGroupSpectatorRoom;
    bool BouncerBouncerDialogDoOnce;
    bool BouncerFirstStreeGuyDoOnce;
    bool BouncerSecondStreeGuyDoOnce;
    FGameplayTagContainer H2_IT06_ENT2;
    FGameplayTagContainer H2_IT11_ENT2;
    FGameplayTagContainer H2_IT12_ENT2;
    FGameplayTagContainer H2_IT07_ENT1;
    bool Does AI Broke the Wall;
    bool Does Fire Disciple Jumped;
    bool LoadingFightingBalcony;
    bool LoadDJ;
    FName SecondFireDisciple Alert Threshold ;
    TArray<class ABP_AiSpawnerGroup_C*> EverySpawnerGroupSecondFireDisciple;
    bool PlayerHasStaffCode;
    FGameplayTagContainer H2_IT08_ENT1;
    FGameplayTagContainer H2_IT08_ENT4;
    FGameplayTagContainer H2_IT10_ENT1;
    FGameplayTagContainer H2_IT10_ENT2;
    bool BouncerHasBeenAlerted;
    bool DoorSoundDoubleFireDisciple;
    bool danceFloorAlertGlobal;
    bool FlashKickDanceFloorDown;
    bool InDoorArea;
    FName Event Triggered;
    bool NMEstillfighting;
    bool GuardAlerted;
    bool SideBalconyAlerted;
    bool SideRoomAlerted;
    int32 indexAIdeath;
    bool TraineesAlerted;
    bool weaponpicked;
    bool 100_allAIdown;
    bool 50_bigGuysResolved;
    bool 50_balconyresolved;
    bool 070_pitFirstOponentDown;
    bool InBossFight;
    TArray<class UAIFightingComponent*> AIdumpedPIT;
    bool SituationIrruptionDone;
    bool 070_Disappearing_Wall_Is_Off;
    TSoftObjectPtr<AActor> LightSwitchBlazingAtrium;
    bool 080_FireDiscipleHasSpawned;
    bool 080_FireDiscipleIntroCineHasPlayed;
    bool 050_BalconyHasSpawned;
    bool trainerAnswer;
    bool 050_GiantAlerted;
    bool TopPitAlerted;
    FString textdebugtest;
    bool DialogHackerStarted;
    TSoftObjectPtr<AActor> PuncinhhBag2;
    TSoftObjectPtr<AActor> PuncinhhBag1;
    bool 100_SituationCompleted;
    TSoftObjectPtr<AActor> PuncinhhBag3;
    TSoftObjectPtr<AActor> PuncinhhBag4;
    TSoftObjectPtr<AActor> FencesToDestroy;
    bool 110_SeanDisappeared;
    TSoftObjectPtr<AActor> danseFloorFlashKick;
    TSoftObjectPtr<AActor> danseFloorDJ;
    TSoftObjectPtr<AActor> BP_VideoSean;
    bool canSeeSean;
    int32 AgeAtBossStart;
    TSoftObjectPtr<AActor> FighterFrontOfSean;
    bool Situation ResolvedSideRoom3;
    class ABaseCharacter* Sean Appearance Character 1;
    class ABaseCharacter* Sean Appearance Character 2;
    class ABaseCharacter* Sean Appearance Character 3;
    class AActor* Sean Appearance Weapon 1;
    class AActor* Sean Appearance Weapon 2;
    class AActor* Sean Appearance Weapon 3;
    class ABP_AiSituation_C* 031_GangLeaderSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 031_BP_GangLeaderSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AISituation_Boss_Sean_C* 140_BP_AISituation_Boss_Sean_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 140_Sean_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 110_DoubleFireDiscipleSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_NightClub_DoorPlaceholder_01_A_C* 110_OpeningDoorsToFireDisciple_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 110_SeanSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 110_SeanSpawner_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Weapon_BoStaff_C* BP_Weapon_BoStaff_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_FireDisciple_Spawner_C* 110_FireDisciple_02_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 110_FireDiscipleSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AStaticMeshActor* 110_ColFakeForDoorSAS_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* 110_gizmoPosForBlockLD_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ALevelSequenceActor* Real_LD_Disciple_Entering_SeanRoom_Shot10_Master_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 130_BP_AiSituation_Guardians_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 130_BP_AiSpawnerGroup_GUARdians_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInteractiveLockableDoorDouble_C* 130_BP_2WaysInteractiveLockableDoorDouble_bigdoor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ASkeletalMeshActor* SK_Grunt_M_Hideout_02_TrainingFighter_06_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_GameplayDoorDouble_C* 100_MidCorridorBlockerDoor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 100_BP_AiSituation_BlazingTrial_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* BP_Sean_Spawner_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_FireDisciple_Spawner_C* 100_SecondFireDisciple_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* 100_FireDiscipleDestination_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_GameplayDoorDouble_C* 100_doorBloc3_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_GameplayDoorDouble_C* 100_doorBloc1_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_GameplayDoorDouble_C* 100_doorBloc2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_GameplayDoorDouble_C* 100_doorBloc4_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 100_DoorKickerBox1_SpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 100_SpawnerGroupBox3_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 100_SpawnerGroupBox4_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 100_SpawnerGroupBox2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 100_UpperSpawnerGroupBox1_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 090_BP_AiSituation_Training_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* SeanIllusionCorridorEndPoint_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInteractiveLockableDoorDouble_C* 100_BP_BlazingAtriumTeleportationDoor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 100_SecondFireDisciple_Group_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* 100_FireDiscipleLookat_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 100_BP_AiSituation_BlazingTrial_FD_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AStaticMeshActor* BlazingPhotoModeConstraint_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 100_DoorKickerBox2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AStaticMeshActor* colProtectSean_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 090_PunchingGruntF_01_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 090_PunchingServant_02_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 090_PunchingServant_03_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 090_PunchingGrunt_02_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 090_GuardTrainingRoom_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInteractiveLockableDoorDouble_C* 090_BP_TraininRoomExitDoor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 080_FireDiscipleSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_FireDisciple_Spawner_C* 080_FireDisciple_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ALevelSequenceActor* Real_LD_intro_FireDisciple_Shot10_Master_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInterractiveLockableDoor_C* 080_DoorsToFireDisciple_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 080_FireDiscipleSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 033_FightingBalconySituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 033_Fighter_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 033_BP_Grunt_Spawner_4_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 033_BP_Grunt_Spawner14_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 033_BP_Grunt_Spawner_5_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 033_MiniBoss_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_GameplayDoorDouble_C* 030_IrruptionSideDanceFloorDoor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 050_VIPSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 050_BigGuySituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 040_SideDanceFloorSituationBackTop_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 040_SideDanceFloorSituationBack_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 040_SideDanceFloorSituationFirst_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 070_BattleRoyalSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 070_SpectatorSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 070_Spectator2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 070_BattleRoyalSpawnerGroup_01_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 071_SeanAppearanceSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 071_BP_SeanSpawner_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 070_BattleRoyalSpawnerGroup_03_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 070_BattleRoyalSpawnerGroup_02_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 070_Spectator1_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 070_Spectator3_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_BigGuy_Spawner_C* 070_BigGuy_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 070_SpectatorSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AStaticMeshActor* CollPhotoModPit_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 050_VIPBalconysituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 050_BarmanSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 050_VIP1_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AIPositionningPOI_C* BP_AIPositionningPOI2_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 050_VIP4_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 050_VIP2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 050_Barman_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 060_FlashKickBarSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 060_FlashKickBarSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_FlashKick_Spawner_C* 060_FlashKickBar_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInteractiveLockableDoorDouble_C* 060_BP_DoorToBettingLounge_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 041_StaffFightSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 041_LightTech_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 040_SpawnerGroupSideRoomSquare_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 040_SpawnerGroupSideRoomBack_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 040_SpawnerGroupSideRoomBackTop_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* 040_GoToActorUpStairsSideRoom_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 040_SpawnerGroupSideRoomBackTopSolo_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 040_GruntSideDanceFloor_02_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* 040_ScreenSean_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 040_ServantSideDanceFloor_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 030_FlashKickSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 030_Dancefloor_Guard_Situation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 030_Dancefloor_01_SpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 030_IrruptionSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 030_IrruptionServant_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 030_IrruptionServant2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_FlashKick_Spawner_C* FlashKickDanceFloor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 032_BP_Grunt_Spawner_DJ_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ALevelSequenceActor* Real_LD_intro_FlashKick_Shot10_Master_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 030_IrruptionDanceFloorSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 032_AISituationActor_DJ_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 020_HostSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 030_Dancefloor_01_SpawnerGroup_Back_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AAISanctuaryVolume* 030_AISanctuaryVolume3_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ASkeletalMeshActor* 032_SK_FlashKick_Hideout_02_Barmaid_01_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ASkeletalMeshActor* 032_SK_Grunt_M_Hideout_02_DJ_01_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* FakeImpact_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInteractiveLockableDoorDouble_C* 030_DanceFloorAnnexeSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 010_CivilianLine2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Servant_Spawner_C* 010_CivilianSittingAlone_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AIPositionningPOI_C* BP_AIPositionningPOI_2_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_Grunt_Spawner_C* 020_HostGuy_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 020_GuardSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSpawnerGroup_C* 020_HostSpawnerGroup_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 010_BouncerSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_AiSituation_C* 010_CivilianSituation_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_BigGuy_Spawner_C* 010_Bouncer_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AActor* 010_PatrolDestination_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class ABP_2WaysInterractiveLockableDoor_C* 090_TrainingRoomEntranceDoor_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AH2_BP_DisappearingWall_C* 070_H2_BP_DisappearingWall_ExecuteUbergraph_Hideout_2_LD_RefProperty;
    class AH2_BP_DisappearingWall_C* 070_H2_BP_DisappearingWall_EdGraph_3_RefProperty;

    bool Is Sean Apparition Visible 1();
    bool Is Sean Apparition Visible 2();
    bool Is Sean Apparition Visible 3();
    bool Is Pit Wall Visible();
    void Is Sean Apparition Visible(int32 Apparition Index, bool& Visible);
    void Save Sean Apparition Character(class ABaseCharacter* Character, int32 Apparition Index);
    void Teleport player(class AActor* Destination);
    void OnFailure_CFADCF374F5669050F34B8BBD251133F();
    void OnSuccess_CFADCF374F5669050F34B8BBD251133F();
    void OnFailure_CFADCF374F5669050F34B8BB98E30876();
    void OnSuccess_CFADCF374F5669050F34B8BB98E30876();
    void OnFailure_CFADCF374F5669050F34B8BB88D50DC6();
    void OnSuccess_CFADCF374F5669050F34B8BB88D50DC6();
    void OnFailure_A4BF9F4940B93FAFE6BE18BF05831908();
    void OnSuccess_A4BF9F4940B93FAFE6BE18BF05831908();
    void OnFailure_A4BF9F4940B93FAFE6BE18BF5CB2B450();
    void OnSuccess_A4BF9F4940B93FAFE6BE18BF5CB2B450();
    void OnFailure_A4BF9F4940B93FAFE6BE18BF38B02EB3();
    void OnSuccess_A4BF9F4940B93FAFE6BE18BF38B02EB3();
    void OnFailure_A4BF9F4940B93FAFE6BE18BFC908CF62();
    void OnSuccess_A4BF9F4940B93FAFE6BE18BFC908CF62();
    void OnFailure_AB269090425225375FAECF9C80A124A2();
    void OnSuccess_AB269090425225375FAECF9C80A124A2();
    void OnFailure_CFADCF374F5669050F34B8BB59633901();
    void OnSuccess_CFADCF374F5669050F34B8BB59633901();
    void OnFailure_CFADCF374F5669050F34B8BB36C3F286();
    void OnSuccess_CFADCF374F5669050F34B8BB36C3F286();
    void OnFailure_D0394C944A86AFA6D356A39D24B364E0();
    void OnSuccess_D0394C944A86AFA6D356A39D24B364E0();
    void OnFailure_CFADCF374F5669050F34B8BBAB03AEF1();
    void OnSuccess_CFADCF374F5669050F34B8BBAB03AEF1();
    void OnFailure_CFADCF374F5669050F34B8BB5E98B100();
    void OnSuccess_CFADCF374F5669050F34B8BB5E98B100();
    void OnInteractiveChoiceSelected_952910CD46784FD1B9FAD3BF9839CA49(int32 DialogNodeId);
    void OnLineEnded_952910CD46784FD1B9FAD3BF9839CA49(int32 DialogNodeId);
    void OnDialogCut_952910CD46784FD1B9FAD3BF9839CA49(int32 DialogNodeId);
    void OnDialogCompleted_952910CD46784FD1B9FAD3BF9839CA49(int32 DialogNodeId);
    void OnInteractiveChoiceSelected_FCC228D74D385AC71FE7B398596EE5E4(int32 DialogNodeId);
    void OnLineEnded_FCC228D74D385AC71FE7B398596EE5E4(int32 DialogNodeId);
    void OnDialogCut_FCC228D74D385AC71FE7B398596EE5E4(int32 DialogNodeId);
    void OnDialogCompleted_FCC228D74D385AC71FE7B398596EE5E4(int32 DialogNodeId);
    void OnInteractiveChoiceSelected_F0E880624BE29F69783625A916C7DB22(int32 DialogNodeId);
    void OnLineEnded_F0E880624BE29F69783625A916C7DB22(int32 DialogNodeId);
    void OnDialogCut_F0E880624BE29F69783625A916C7DB22(int32 DialogNodeId);
    void OnDialogCompleted_F0E880624BE29F69783625A916C7DB22(int32 DialogNodeId);
    void OnInteractiveChoiceSelected_254B5A164B66A5E7C5E86A98463DCAAF(int32 DialogNodeId);
    void OnLineEnded_254B5A164B66A5E7C5E86A98463DCAAF(int32 DialogNodeId);
    void OnDialogCut_254B5A164B66A5E7C5E86A98463DCAAF(int32 DialogNodeId);
    void OnDialogCompleted_254B5A164B66A5E7C5E86A98463DCAAF(int32 DialogNodeId);
    void NothingToSpawn_FFADCF9E41FD2937C88BB7BFA1A80C89();
    void AllSpawned_FFADCF9E41FD2937C88BB7BFA1A80C89();
    void OnInteractiveChoiceSelected_B97D624F4134C209EDD6C4BAF4BA33B8(int32 DialogNodeId);
    void OnLineEnded_B97D624F4134C209EDD6C4BAF4BA33B8(int32 DialogNodeId);
    void OnDialogCut_B97D624F4134C209EDD6C4BAF4BA33B8(int32 DialogNodeId);
    void OnDialogCompleted_B97D624F4134C209EDD6C4BAF4BA33B8(int32 DialogNodeId);
    void OnInteractiveChoiceSelected_D13C890F417B706D29F1E7B17926162A(int32 DialogNodeId);
    void OnLineEnded_D13C890F417B706D29F1E7B17926162A(int32 DialogNodeId);
    void OnDialogCut_D13C890F417B706D29F1E7B17926162A(int32 DialogNodeId);
    void OnDialogCompleted_D13C890F417B706D29F1E7B17926162A(int32 DialogNodeId);
    void OnInteractiveChoiceSelected_67B106F94A50536424161E8F1D1A88FD(int32 DialogNodeId);
    void OnLineEnded_67B106F94A50536424161E8F1D1A88FD(int32 DialogNodeId);
    void OnDialogCut_67B106F94A50536424161E8F1D1A88FD(int32 DialogNodeId);
    void OnDialogCompleted_67B106F94A50536424161E8F1D1A88FD(int32 DialogNodeId);
    void NothingToSpawn_8CCE57194A48728373F121AD4BE8D7B1();
    void AllSpawned_8CCE57194A48728373F121AD4BE8D7B1();
    void Aquarium Situation();
    void BndEvt__TriggerBox55_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void SaveWhenAllAIAreDead(class ABaseCharacter* _character);
    void Spawn Sean();
    void SeanDeathPhase3(class ABaseCharacter* _character);
    void BndEvt__TriggerBox28_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void Delete fire discple(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_140_TRG_LaunchIntroSean2_K2Node_ActorBoundEvent_1_VolumeBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void UnlocktrophyWude(class USCAbilitySystemComponent* _abilityComponent, const FGameplayTag& _tag, int32 _iCount);
    void UnlockTrophyDeath(class USCAbilitySystemComponent* _abilityComponent, const FGameplayTag& _tag, int32 _iCount);
    void BPE_OnEndAIPhaseChanged(class AFightingCharacter* _fightingChar, int32 _iPreviousPhaseIndex, int32 _iCurrentPhaseIndex);
    void BndEvt__Hideout_2_LD_120_FireStreet_Checkpoint_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void RingRoom_SpawnSituation(class AActor* OverlappedActor, class AActor* OtherActor);
    void RingRoomPerceptionOff(class AActor* OverlappedActor, class AActor* OtherActor);
    void PostProcessSituation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox29_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox32_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void triggerFight(EThrowableState _eNewState);
    void BndEvt__Hideout_2_LD_110_TRG_ForceFD_K2Node_ActorBoundEvent_4_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_110_DoubleFireDiscipleSituation_K2Node_ActorBoundEvent_5_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void On Sean Apparition 3 spawned(class AAISituationActor* SituationChanged);
    void Spawn_Village_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox50_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_130_BP_DoorToVillage_K2Node_ActorBoundEvent_3_SequenceStarted__DelegateSignature(bool StartedWay1);
    void clean situation();
    void BndEvt__Hideout_2_LD_120_TRG_SaveWhenReachingVillage2_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void Spawn_SpectatorRoom(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__090_SpawnCorridorFightTrigger_K2Node_ActorBoundEvent_20_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__100_TRG_SpawnFireDisciple_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_100_TRG_AlertAIBox3_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void AllAIDown(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_100_TRG_AlertFireDiscipleRight_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_100_BP_BlazingAtriumTeleportationDoor_K2Node_ActorBoundEvent_1_SequenceFinished__DelegateSignature();
    void triggerUpperPart();
    void OnSeanSpawned(class ABaseCharacter* _character);
    void 100_FireDisciple_Dialog(FName EventTriggered);
    void BndEvt__Hideout_2_LD_100_TRG_AlertFireDiscipleRight_K2Node_ActorBoundEvent_0_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void OnFDdown(class ABaseCharacter* _character);
    void RestartFinalDialog();
    void 100_RespawnFD();
    void FDtriggerAfterFight(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void OnFDDeathEnd(class ABaseCharacter* _character);
    void Spawn_TrainingRoom_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_090_BP_AiSituation_Training_K2Node_ActorBoundEvent_1_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void AllTraineesAttack(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void launchCombo();
    void BndEvt__Hideout_2_LD_090_TRG_Trainee01_close2_K2Node_ActorBoundEvent_2_VolumeBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Hideout_2_LD_090_TRG_Trainee01_close_K2Node_ActorBoundEvent_3_VolumeBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Hideout_2_LD_090_TRG_Trainee01_close3_K2Node_ActorBoundEvent_4_VolumeBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Hideout_2_LD_090_TRG_Trainee01_close4_K2Node_ActorBoundEvent_5_VolumeBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Hideout_2_LD_090_TRG_AlertGuardTrainingRoom_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_090_BP_TraininRoomExitDoor_K2Node_ActorBoundEvent_8_SequenceFinished__DelegateSignature();
    void BndEvt__Hideout_2_LD_090_TRG_AlertGuardTrainingRoom_K2Node_ActorBoundEvent_7_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void Spawn_FirstFireDisciple_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void OnFDDefeated(class ABaseCharacter* _character);
    void OnFinished_Event_0();
    void BndEvt__Hideout_2_LD_080_DoorsToFireDisciple_K2Node_ActorBoundEvent_5_On Use Interaction__DelegateSignature(bool Way 1);
    void BndEvt__Hideout_2_LD_080_FireDiscipleSituation_K2Node_ActorBoundEvent_0_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void CheckpointLoadNightClubSetting();
    void Spawn_Fighting_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox47_15_K2Node_ActorBoundEvent_47_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_033_TRG_SecondFightApproach_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_033_TRG_SecondFight_Alert_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_033_TRG_thirdFightApproach_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_033_TRG_thirdFightAlert_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_033_TRG_Boss_K2Node_ActorBoundEvent_4_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_033_FightingBalconySituation_K2Node_ActorBoundEvent_2_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void BndEvt__Hideout_2_LD_033_DoorFightingBalcony_K2Node_ActorBoundEvent_4_SequenceStarted__DelegateSignature(bool StartedWay1);
    void The_Piit_Spawn(class AActor* OverlappedActor, class AActor* OtherActor);
    void The_Pit_Dialogues(class AActor* OverlappedActor, class AActor* OtherActor);
    void The_Pit_Killing(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox26_3_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox64_3_K2Node_ActorBoundEvent_63_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox60_K2Node_ActorBoundEvent_12_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void DeathAIPit(class ABaseCharacter* _character);
    void BndEvt__TriggerBox5_3_K2Node_ActorBoundEvent_50_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_070_TRG_JumpingIntoThePit_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_070_BattleRoyalSituation_K2Node_ActorBoundEvent_4_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void BndEvt__Hideout_2_LD_070_BattleRoyalSituation_K2Node_ActorBoundEvent_0_EventWithCharacterDynamic__DelegateSignature(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_070_SpectatorSituation_K2Node_ActorBoundEvent_0_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void Spectator behavior change(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void switchPitSettingReload();
    void TranstionPitStep(int32 NewParam);
    void BndEvt__Hideout_2_LD_070_TRG_phoneconv_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void VIP_Balcony_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox13_3_K2Node_ActorBoundEvent_8_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_051_TRG_AlerteSideBalcony_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_050_VIPSituation_K2Node_ActorBoundEvent_1_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void triggerAbandonforBarman(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_050_VIPSituation_K2Node_ActorBoundEvent_7_AISituationGlobalBehaviorChangedDynamic__DelegateSignature(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void CheckLastAI(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_050_BarmanSituation_K2Node_ActorBoundEvent_6_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void CustomEvent_0(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_050_VIPSituation_K2Node_ActorBoundEvent_2_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void BndEvt__Hideout_2_LD_050_BigGuySituation_K2Node_ActorBoundEvent_3_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void BndEvt__Hideout_2_LD_SCVolume2_3_K2Node_ActorBoundEvent_4_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BarmanChangeB(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_050_BigGuySituation_K2Node_ActorBoundEvent_9_AISituationGlobalBehaviorChangedDynamic__DelegateSignature(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_050_LeftWing_Checkpoint_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void Flashkick_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_060_TRG_AlertFlashKickBarSituation_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_060_TRG_startFight_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_060_TRG_startFightBehingBar_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_060_FlashKickBarSituation_K2Node_ActorBoundEvent_2_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void BndEvt__Hideout_2_LD_060_BP_DoorToBettingLounge_K2Node_ActorBoundEvent_4_SequenceFinished__DelegateSignature();
    void Secret_Staff_Event(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_041_TRG_SpawnStaffSituationTrigger2_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_041_TRG_ShutDownDialog_K2Node_ActorBoundEvent_8_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void CustomEvent(class ABaseCharacter* _character);
    void BlackRoom_Situation(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox6_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void SpawnSideRoom(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_040_TRG_InSquareVIP_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_040_GruntSideDanceFloor_01_K2Node_ActorBoundEvent_3_AICharacterGlobalBehaviorChanged__DelegateSignature(class ABaseCharacter* Character, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_040_SideDanceFloorSituationFirst_K2Node_ActorBoundEvent_2_EventWithCharacterDynamic__DelegateSignature(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_040_TRG_InBackAlert_K2Node_ActorBoundEvent_4_VolumeBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Hideout_2_LD_050_BP_DoorToLeftWing_K2Node_ActorBoundEvent_4_SequenceFinished__DelegateSignature();
    void BndEvt__Hideout_2_LD_040_SideDanceFloorSituationBack_K2Node_ActorBoundEvent_9_On All AIs Died__DelegateSignature();
    void BndEvt__Hideout_2_LD_050_TRG_SuspiciousTop_K2Node_ActorBoundEvent_13_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_050_TRG_AlertTop_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_050_TRG_AlertTop_K2Node_ActorBoundEvent_1_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_040_SideDanceFloorSituationBack_K2Node_ActorBoundEvent_10_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void AIBacktriggered(class ABaseCharacter* Character, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_040_TRG_TriggerSoloAI_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_040_SideDanceFloorSituationBackTop_K2Node_ActorBoundEvent_12_On All AIs Died__DelegateSignature();
    void SpawnDanceFloor();
    void FirstRefill(class ABaseCharacter* _character);
    void OnSaveLoadedDanceFloor();
    void OpeningSideDoorTets(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_030_FlashKickSituation_K2Node_ActorBoundEvent_1_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void BndEvt__Hideout_2_LD_030_TGR_Suspicious1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_030_TGR_Suspicious5_K2Node_ActorBoundEvent_4_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_030_TGR_Suspicious4_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_030_TGR_tooCloseGroup3_K2Node_ActorBoundEvent_10_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_030_TGR_DoorNextStep_K2Node_ActorBoundEvent_11_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_040_TRG_testIfNMEStillStand_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_030_IrruptionSituation_K2Node_ActorBoundEvent_7_On All AIs Died__DelegateSignature();
    void BndEvt__Hideout_2_LD_032_AISituationActor_DJ_K2Node_ActorBoundEvent_4_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void RespawnIrruptionSave();
    void BndEvt__Hideout_2_LD_020_DoorDanceFloorSasExit_K2Node_ActorBoundEvent_2_SequenceFinished__DelegateSignature();
    void BndEvt__Hideout_2_LD_030_IrruptionSituation_K2Node_ActorBoundEvent_6_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void Spawn Situations Host();
    void UnspawnCivilians();
    void HostFightStart(FName EventTriggered);
    void BndEvt__TriggerBox18_6_K2Node_ActorBoundEvent_19_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_020_HostSituation_K2Node_ActorBoundEvent_0_EventWithCharacterDynamic__DelegateSignature(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_020_TriggerAlertHost_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_030_TRG_activityUpdate_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox33_2_K2Node_ActorBoundEvent_30_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_020_TriggerAlert1_K2Node_ActorBoundEvent_4_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__Hideout_2_LD_020_TriggerAlert2_K2Node_ActorBoundEvent_5_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void HostTriggerToFight(class ABaseCharacter* Character, EGlobalBehaviors NewBehavior);
    void CustomEvent_3(EAlertLevel EAlertLevel);
    void Spawn Bouncer();
    void BndEvt__TriggerBox23_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox40_3_K2Node_ActorBoundEvent_43_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void FleeingCivilians(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void TriggerAbandonCivilians(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__TriggerBox51_3_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void CivilAbandon(class AAISituationActor* SituationChanged, const class UAIFightingComponent* AI, EGlobalBehaviors NewBehavior);
    void BndEvt__Hideout_2_LD_010_CivilianSituation_K2Node_ActorBoundEvent_1_EventWithCharacterDynamic__DelegateSignature(class ABaseCharacter* _character);
    void BndEvt__Hideout_2_LD_010_BouncerSituation_K2Node_ActorBoundEvent_4_AISituationDynamicMulticastDelegate__DelegateSignature(class AAISituationActor* SituationChanged);
    void GoToTeleport();
    void BndEvt__BP_DebugTeleportManager_2_K2Node_ActorBoundEvent_8_ED_TeleportLaunched__DelegateSignature(int32 ID);
    void BndEvt__020_TriggerBox_01_K2Node_ActorBoundEvent_17_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox_5_K2Node_ActorBoundEvent_20_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox_10_K2Node_ActorBoundEvent_26_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void ReceiveBeginPlay();
    void BndEvt__TriggerBox2_3_K2Node_ActorBoundEvent_31_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox10_15_K2Node_ActorBoundEvent_15_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox14_24_K2Node_ActorBoundEvent_22_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox25_27_K2Node_ActorBoundEvent_25_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox26_3_K2Node_ActorBoundEvent_7_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox3_3_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox9_3_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox17_3_K2Node_ActorBoundEvent_18_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox23_3_K2Node_ActorBoundEvent_23_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox24_6_K2Node_ActorBoundEvent_24_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox29_3_K2Node_ActorBoundEvent_10_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox35_3_K2Node_ActorBoundEvent_38_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox7_3_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox38_3_K2Node_ActorBoundEvent_41_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox39_3_K2Node_ActorBoundEvent_42_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox4_6_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__TriggerBox58_3_K2Node_ActorBoundEvent_56_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BndEvt__SCPlayerVolume_1_K2Node_ActorBoundEvent_53_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void Trying Brasero(class AActor* AIRespawned);
    void BndEvt__TriggerBox21_3_K2Node_ActorBoundEvent_20_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void BPE_OnUpdatedFromSave();
    void BndEvt__TriggerBox8_3_K2Node_ActorBoundEvent_8_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
    void On Open Training Room Door(bool Way 1);
    void On Use Interaction_Event(bool Way 1);
    void Set Sean Apparition Visible(bool Visible, int32 Apparition Index);
    void Set Sean Apparition Visible Rep 1(bool Visible);
    void Set Sean Apparition Visible Rep 2(bool Visible);
    void Set Sean Apparition Visible Rep 3(bool Visible);
    void Set Pit Wall Visible(bool Visible);
    void ExecuteUbergraph_Hideout_2_LD(int32 EntryPoint);
};

#endif
