#ifndef UE4SS_SDK_HittedGetUpNoAttackAvailabilityOrderService_HPP
#define UE4SS_SDK_HittedGetUpNoAttackAvailabilityOrderService_HPP

class UHittedGetUpNoAttackAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
