#ifndef UE4SS_SDK_KnockdownGetUpRedirectOrderService_HPP
#define UE4SS_SDK_KnockdownGetUpRedirectOrderService_HPP

class UKnockdownGetUpRedirectOrderService_C : public URedirectToTargetOrderService
{
};

#endif
