#ifndef UE4SS_SDK_KnockdownDisableCollisionOrderService_HPP
#define UE4SS_SDK_KnockdownDisableCollisionOrderService_HPP

class UKnockdownDisableCollisionOrderService_C : public UDisableCollisionOrderService
{
};

#endif
