#ifndef UE4SS_SDK_KnockdownALOrderService_AIDefense_HPP
#define UE4SS_SDK_KnockdownALOrderService_AIDefense_HPP

class UKnockdownALOrderService_AIDefense_C : public UAvailabilityLayerOrderService
{
};

#endif
