#ifndef UE4SS_SDK_MainChar_ElbowSync_SynchronizedHitAction_HPP
#define UE4SS_SDK_MainChar_ElbowSync_SynchronizedHitAction_HPP

class UMainChar_ElbowSync_SynchronizedHitAction_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
