#ifndef UE4SS_SDK_MakeShift_ThrowFromPickupTargetSettingsDB_HPP
#define UE4SS_SDK_MakeShift_ThrowFromPickupTargetSettingsDB_HPP

class UMakeShift_ThrowFromPickupTargetSettingsDB_C : public UTargetSettingsDB
{
};

#endif
