#ifndef UE4SS_SDK_MC_Blades_Charged_Attack_SynchronizedHitAction_HPP
#define UE4SS_SDK_MC_Blades_Charged_Attack_SynchronizedHitAction_HPP

class UMC_Blades_Charged_Attack_SynchronizedHitAction_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
