#ifndef UE4SS_SDK_OrderSynchronizedAttackInvertPositionInstigator_HPP
#define UE4SS_SDK_OrderSynchronizedAttackInvertPositionInstigator_HPP

class UOrderSynchronizedAttackInvertPositionInstigator_C : public UOrderSynchronizedAttackInstigator_C
{
};

#endif
