#ifndef UE4SS_SDK_OrderTakedownTransitionInstigator_HPP
#define UE4SS_SDK_OrderTakedownTransitionInstigator_HPP

class UOrderTakedownTransitionInstigator_C : public UOrderSynchronizedAttackInstigator_C
{
};

#endif
