#ifndef UE4SS_SDK_PushFromGrab_AllAvailabilityOrderService_HPP
#define UE4SS_SDK_PushFromGrab_AllAvailabilityOrderService_HPP

class UPushFromGrab_AllAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
