#ifndef UE4SS_SDK_PushFromGrab_AttacksAvailabilityOrderService_HPP
#define UE4SS_SDK_PushFromGrab_AttacksAvailabilityOrderService_HPP

class UPushFromGrab_AttacksAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
