#ifndef UE4SS_SDK_SkillGameplay_Action_OTGParryCounter_HPP
#define UE4SS_SDK_SkillGameplay_Action_OTGParryCounter_HPP

class USkillGameplay_Action_OTGParryCounter_C : public USkillGameplay_Action_C
{
};

#endif
