#ifndef UE4SS_SDK_SkillGameplay_Technique_PostPushbackKnockdown_HPP
#define UE4SS_SDK_SkillGameplay_Technique_PostPushbackKnockdown_HPP

class USkillGameplay_Technique_PostPushbackKnockdown_C : public USkillGameplay_Technique_C
{
};

#endif
