#ifndef UE4SS_SDK_SkillGameplay_Action_UseDamagedWeapon_HPP
#define UE4SS_SDK_SkillGameplay_Action_UseDamagedWeapon_HPP

class USkillGameplay_Action_UseDamagedWeapon_C : public USkillGameplay_Action_C
{
};

#endif
