#ifndef UE4SS_SDK_WBP_ReplayManagement_HPP
#define UE4SS_SDK_WBP_ReplayManagement_HPP

class UWBP_ReplayManagement_C : public UReplayManagementMenuWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* Background;
    class UBP_Menu_Popup_Validation_C* BP_Menu_Popup_Confirm_Delete;
    class UBP_Menu_Popup_Validation_C* BP_Menu_Popup_Confirm_Load;
    class UBP_Menu_Popup_Validation_C* BP_Menu_Popup_Confirm_Reset;
    class UBP_Btn_ReplayManagement_Action_C* Btn_BackToEdit;
    class UBP_Btn_ReplayManagement_Action_C* Btn_Delete;
    class UBP_Btn_ReplayManagement_Action_C* Btn_Edit;
    class UBP_Btn_ReplayManagement_Action_C* Btn_Reset;
    class UBP_Btn_InputTip_C* BtnBack;
    class UTextBlock* CantCreatenew;
    class UCanvasPanel* CurrentReplayCanvas;
    class UBorder* CurrentReplaySpace_Border;
    class UTextBlock* ErrorMessage;
    class UTextBlock* ErrorMessageReason;
    class UHorizontalBox* FreeSpace_HorizontalBox;
    class UScrollBox* GameplayScroll;
    class UVerticalBox* HorizontalBox_Buttons;
    class UWidgetSwitcher* LoadingSwitcher;
    class UHorizontalBox* MaxReplaySizeVisualClue;
    class UTextBlock* MaxSizeTxt;
    class UBorder* OccupiedSpace_Border;
    class USpacer* OccupiedSpacer;
    class UCanvasPanel* Popup_Confirm;
    class UOverlay* RecordInteruptPanel;
    class UWidgetSwitcher* ReplayCountSwitcher;
    class UTextBlock* ReplayCountTxt;
    class UTextBlock* ReplayCountWarningTxt;
    class UBorder* ReplaySizeClue_Border;
    class USpacer* ReplaySizeClue_Spacer;
    class UTextBlock* ReplaySizeTxt;
    class UTextBlock* ReplayTitle;
    class UTextBlock* ShouldDeleteOld;
    class UHorizontalBox* SpaceOccupied_HorizontalBox;
    class UThrobber* Throbber_102;
    class UTextBlock* TitleTextOverride;
    class UHorizontalBox* TooManyReplaysPanel;
    class UTextBlock* TooManyReplaysText;
    class UImage* WarningImg;
    class UImage* WarningImg_1;
    class UHorizontalBox* WarningPanel;
    class UWidgetSwitcher* WarningSwitcher;
    FWBP_ReplayManagement_CEnterReplayRequestedDispatcher EnterReplayRequestedDispatcher;
    void EnterReplayRequestedDispatcher();
    FWBP_ReplayManagement_COnBackRequested OnBackRequested;
    void OnBackRequested();
    FWBP_ReplayManagement_COnReplayEditorBackRequested OnReplayEditorBackRequested;
    void OnReplayEditorBackRequested();
    bool bStreamerTaskRunning;
    FString StreamerTaskRunningName;
    class UWBP_ReplayManagementItem_C* SelectedReplay;
    FReplaySizeManagement ReplaySizeManagement;
    FLinearColor OutOfSpaceBrush;
    FLinearColor NotOutOfSpaceBrush;
    bool HasCustomQuit;
    TMap<class FString, class UTexture2D*> ReplayImagesByMaps;
    FWBP_ReplayManagement_COnQuitReplayManagement OnQuitReplayManagement;
    void OnQuitReplayManagement(bool HasLaunchedReplay);

    void UpdateReplayCount();
    void GetReplayImageFromMap(FString MapFriendlyName, class UTexture2D*& Texture);
    void ShowPopup(class UBP_Menu_Popup_Validation_C* Popup);
    void YesConfirmationLoadPopup();
    void NoConfirmationLoadPopup();
    void UpdateWarnings();
    void YesConfirmationResetPopup();
    void NoConfirmationResetPopup();
    void NoConfirmationDeletePopup();
    void YesConfirmationDeletePopup();
    void UpdateOutOfSpaceFeedbacks();
    void UpdateSpaceFeedbacks(class UWBP_ReplayManagementItem_C* SelectedItem);
    void FocusOnFirstReplay();
    void FocusOnCurrentReplay();
    bool BPE_OnInputAction(InputAction eAction);
    void OnReplayClicked(class UWBP_ReplayManagementItem_C* Replay Management Item);
    void OnReplayFocusChanged(bool IsFocused, class UWBP_ReplayManagementItem_C* Instance);
    void OnReplayManagementTaskStateChanged(bool _bIsTaskRunning, FString _taskName);
    void OnBackReplayEditorClic(class UButtonUserWidget* _button, bool _bWithMouse);
    void OnBackClic(class UButtonUserWidget* _button, bool _bWithMouse);
    void OnReplayEditRequested();
    void OnReplayResetRequested();
    void OnReplayExportRequested();
    void OnReplayDeleteRequested();
    void ClearAllItems();
    void Construct();
    void BPE_OnStreamsEnumerated(bool _bError, const FReplayListInfo& _replayInfos);
    void BPE_OnStreamDeleted(bool _bError);
    void Destruct();
    void BndEvt__WBP_ReplayManagement_Btn_Reset_K2Node_ComponentBoundEvent_7_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__WBP_ReplayManagement_Btn_Delete_K2Node_ComponentBoundEvent_8_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BPE_OnVisible();
    void OnReplayManagementReady();
    void OnWaitKeepReplayToComplete();
    void OnKeepReplayCompleted();
    void BndEvt__WBP_ReplayManagement_Btn_Edit_K2Node_ComponentBoundEvent_4_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BPE_OnMenuTransitionIn(EMenuTransitions _eTransition, EMenuEnum _ePrevMenu);
    void BPE_OnMenuTransitionOut(EMenuTransitions _eTransition, EMenuEnum _eNewMenu);
    void ExecuteUbergraph_WBP_ReplayManagement(int32 EntryPoint);
    void OnQuitReplayManagement__DelegateSignature(bool HasLaunchedReplay);
    void OnReplayEditorBackRequested__DelegateSignature();
    void OnBackRequested__DelegateSignature();
    void EnterReplayRequestedDispatcher__DelegateSignature();
};

#endif
