#ifndef UE4SS_SDK_WBP_ReplayEditorMain_HPP
#define UE4SS_SDK_WBP_ReplayEditorMain_HPP

class UWBP_ReplayEditorMain_C : public UReplayMainUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* NotificationAnimation;
    class UWBP_ReplayEditorBottomInputDisplay_C* BackInputDisplay;
    class UImage* BG_CameraControlaTitle;
    class UCanvasPanel* CameraControlPanel;
    class UVerticalBox* CameraControlsVerticalBox;
    class UWBP_PhotomodeSideInputDisplay_C* CameraInputs;
    class UCanvasPanel* CurrentModeTopPanel;
    class UWBP_ReplayFreecamPositionUpdate_Availability_C* FreeCamUpdateWindow;
    class UWBP_AvailableInputContainer_C* InputContainer_NavigationMode;
    class UWBP_AvailableInputContainer_C* InputContainer_Resume;
    class UWBP_AvailableInputContainer_C* InputContainer_Scrub_1;
    class UWBP_AvailableInputContainer_C* InputContainer_SelectNextPreviousKey;
    class UWBP_AvailableInputContainer_C* InputContainer_Zoom;
    class UTextBlock* InputText_NavigationMode;
    class UTextBlock* InputText_Resume;
    class UTextBlock* InputText_Scrub_1;
    class UTextBlock* InputText_SelectNextPreviousKey;
    class UTextBlock* InputText_Zoom;
    class UBP_Btn_InputTip_C* InputTip_NavigationMode;
    class UBP_Btn_InputTip_C* InputTip_Resume;
    class UBP_Btn_InputTip_ConsoleOverride_C* InputTip_ScrubConsole;
    class UBP_Btn_InputTip_ConsoleOverride_C* InputTip_SelectKeyConsole;
    class UBP_Btn_InputTip_ConsoleOverride_C* InputTip_TimelineZoomConsole;
    class UBorder* NotificationPanel;
    class UTextBlock* NotificationText;
    class UImage* PageTitleBG;
    class UWBP_PhotomodeSideInputDisplay_C* SideInputDisplay;
    class UBackgroundBlur* TimelineBGBlur;
    class UCanvasPanel* TimelineInputs;
    class UOverlay* TimelineOverlay;
    class UTextBlock* TitleTextOverride;
    class UWBP_ApplyCameraSettingsTooltip_C* WBP_ApplyCameraSettingsTooltip;
    class UWBP_BrowseMenu_C* WBP_BrowseMenu;
    class UWBP_ReplayTextKeyStateAvailability_C* WBP_ReplayTextKeyStateAvailability;
    class UWBP_ReplaySubMenuContainer_C* WBP_Settings;
    FWBP_ReplayEditorMain_CNavigationKeyDownDispatcher NavigationKeyDownDispatcher;
    void NavigationKeyDownDispatcher(FKey Key);
    class UWBP_ExportScreenVideoPopup_C* BP_ExportMenuPopup;
    TEnumAsByte<ReplayExportType> CurrentExportMode;
    class UWBP_FilterPresetSavedPopup_C* FilterPresetSavedPopup;
    class UWBP_ReplayManagement_C* WBP_ReplayManagementMenu;
    class UBP_PresetKeySelectionMenuReplayEditor_C* WBP_PresetKeySelectionMenu;
    bool ApplyPhotoSettingsToFreefly;
    FAvailabilityLayerCache KeyJumpAvailabilityLayer;
    FAvailabilityLayerCache ScrubAvailabilityLayer;
    bool bNeedPushSettings;

    bool BPE_OnHideUIPressed();
    void PlayNotificationAnimation(FText NotificationText);
    void Format Input Timeline Text(bool IsWhite, bool IsPrimary, class UTextBlock* Text);
    void ChangeTimelineStyle(bool IsWhite, bool IsFocus);
    void RemoveNavigationModeLayers();
    void SwapNavigationMode();
    bool BPE_OnNavigationModePressed();
    void OnCameraCutUpdated(bool CutActive);
    void OnKeySelected(bool OpenSettings, int32 KeyType, EReplayKeyTransition BlendType, EReplayKeyCameraMode CameraMode, FReplayKeyScreenFading FadeInfo);
    bool BPE_OnReplayQuitPressed();
    bool BPE_OnMenuOptionsPressed();
    void OnBackMenuKeySelection();
    void OpenKeySelectionMenu();
    bool SubMenuContainerAvailabilityOverride(const class UReplaySubMenuWidget* _menu);
    void OnGoToTimeCompleted();
    void OnBlendProfileUpdated();
    void SelectCurrentKeyIfExists();
    void OnCameraFocusUpdated();
    void OnCameraSettingsChanged();
    void OnCameraSettingsUpdated(bool DisplayCameraSettings);
    void ClearSelectedKey();
    void OnMenuFocused(bool Focused);
    void OnCameraModeUpdated();
    void CameraPropertyEdited(class UBindablePropertyBase* Property);
    void UpdateTitleDisplay(bool InPreview);
    void BindSettings();
    bool BPE_OnMenuRightPressed();
    bool BPE_OnMenuLeftPressed();
    bool BPE_OnTakeScreenshotPressed();
    bool BPE_OnReplayJumpStart();
    bool BPE_OnReplayJumpEnd();
    bool BPE_OnVideoRecordingStop();
    void OnBackReplayManagementRequested();
    void OnQuitReplayEditorRequested();
    bool BPE_OnMenuActionPressed();
    bool BPE_OnPasteKeyPressed();
    bool BPE_OnCopyKeyPressed();
    void BPE_OnUndoOrRedoPressed(const ETimelineStateAction _eAction, const FTimelineChangeState& _changeState);
    bool BPE_OnEditReplayPressed();
    bool BPE_OnTimelineZoom(float _fActionValue);
    void ForceInputDisplayRefresh();
    bool BPE_OnSelectCurrentKeyPressed();
    void GetBrowseInputAvailability(bool& _bOutAvailable);
    bool BPE_OnRemoveCutPressed();
    bool BPE_OnMoveKeyReleased();
    bool BPE_OnMoveKeyRightPressed();
    bool BPE_OnMoveKeyLeftPressed();
    bool BPE_OnAddCutPressed();
    bool BPE_OnAddSpeedKeyPressed();
    void On Add Key Pressed(int32 KeyType, EReplayKeyTransition BlendType, EReplayKeyCameraMode CameraMode, FReplayKeyScreenFading FadeInfo, bool OpenSettingsAfter, bool& InputConsummed);
    bool BPE_OnLeaveModePressed();
    bool BPE_OnApplyFocusPressed();
    bool BPE_OnApplySettingsPressed();
    bool BPE_OnExportPressed();
    void OnVideoRecorderCreated(class AReplayVideoRecorder* VideoRecorder);
    void OnVideoRecordingCompleted(bool Success);
    void OnVideoRecordingStarted(bool Success);
    void ExportVideo();
    void HideExportPopup();
    void ShowExportPopup();
    void CreateExportPopup(const FCreateExportPopupOnBackRequested& OnBackRequested, const FCreateExportPopupOnExportScreen& OnExportScreen, const FCreateExportPopupOnExportVideo& OnExportVideo);
    bool OnExportPressed();
    bool ToggleTimelineMode();
    void Update Current Camera Settings(class UReplayKey* Key);
    bool BPE_OnMenuInputPressed(InputAction _eAction);
    void GetReplayController(class ABP_ReplayController_C*& Controller);
    void OnKeyPropertyPreEdited(class UBindablePropertyBase* Property);
    void DisplayKeyEditMenu();
    void SelectRightKey();
    void SelectLeftKey();
    void OnSelectLeftOrRightKey();
    FEventReply OnPreviewKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    void GetTimelineModel(class UReplayTimelineModel*& TimelineModel);
    bool BPE_OnTimelineMoveForwardPressed();
    bool BPE_OnTimelineMoveBackwardPressed();
    bool BPE_OnScrubReleased();
    bool BPE_OnEditCameraPressed();
    bool BPE_OnMenuBackKeyPressed();
    bool BPE_OnRemoveKeyPressed();
    bool BPE_OnSelectRightKeyPressed();
    bool BPE_OnSelectLeftKeyPressed();
    bool BPE_OnAddKeyPressed();
    bool BPE_OnResumePressed();
    void RebindEditorProperties(const class UReplayKey*& Key);
    void Construct();
    void BPE_OnKeyAdded(class UReplayKey* _key);
    void OnCachedGeometryAvailableEvent();
    void ApplyCameraSettingsDefaultsToDummy();
    void OnKeyDownDispatch(FKey Key);
    void BPE_OnCameraModeChanged(EReplayCameraMode _eCameraMode);
    void BPE_OnPreviewModeChanged(bool _bInPreview);
    void BndEvt__WBP_ReplayEditorMain_m_TimelineWidget_K2Node_ComponentBoundEvent_0_OnCachedGeometryAvailableDispatcher__DelegateSignature();
    void BPE_OnKeySelectionUpdate(class UReplayKey* _key, bool _bSelected);
    void BPE_OnSelectedKeyDataUpdate(class UReplayKey* _key, const FReplayKeyData& _previousData);
    void ApplyCameraSettingsDefaults(class UReplayKey* Key);
    void ApplyVirtualCameraSettings(class UReplayKey* Key);
    void BPE_OnTimelineModeToggled();
    void ApplyVirtualCameraSettingsToDummy();
    void BPE_OnRemovedFromParent();
    void BndEvt__WBP_ReplayEditorMain_WBP_Settings_K2Node_ComponentBoundEvent_1_OnMenuCycle__DelegateSignature(class UWBP_ReplaySubMenuBase_C* Previous, class UWBP_ReplaySubMenuBase_C* Next);
    void BndEvt__WBP_ReplayEditorMain_WBP_Settings_K2Node_ComponentBoundEvent_2_OnAnyPropertyPreEdit__DelegateSignature(class UBindablePropertyBase* _property, class UWBP_ReplaySubMenuWithProperties_C* Menu);
    void BndEvt__WBP_ReplayEditorMain_WBP_Settings_K2Node_ComponentBoundEvent_0_OnMenuPoppedDispatcher__DelegateSignature();
    void BndEvt__WBP_ReplayEditorMain_WBP_Settings_K2Node_ComponentBoundEvent_4_OnPhotoSettingsAspectRatioUpdated__DelegateSignature();
    void BndEvt__WBP_ReplayEditorMain_WBP_Settings_K2Node_ComponentBoundEvent_5_OnPhotoSettingsPostProcessUpdated__DelegateSignature();
    void BPE_OnKeyPastedOn(class UReplayKey* _key, bool _bIsNew);
    void BndEvt__WBP_ReplayEditorMain_InputContainer_Zoom_K2Node_ComponentBoundEvent_6_OnVisibilityChangedEvent__DelegateSignature(ESlateVisibility InVisibility);
    void BndEvt__WBP_ReplayEditorMain_InputContainer_Resume_K2Node_ComponentBoundEvent_7_OnVisibilityChangedEvent__DelegateSignature(ESlateVisibility InVisibility);
    void BndEvt__WBP_ReplayEditorMain_InputContainer_NavigationMode_K2Node_ComponentBoundEvent_8_OnVisibilityChangedEvent__DelegateSignature(ESlateVisibility InVisibility);
    void BndEvt__WBP_ReplayEditorMain_InputContainer_SelectNextPreviousKey_K2Node_ComponentBoundEvent_10_OnVisibilityChangedEvent__DelegateSignature(ESlateVisibility InVisibility);
    void BndEvt__WBP_ReplayEditorMain_InputContainer_Scrub_1_K2Node_ComponentBoundEvent_11_OnVisibilityChangedEvent__DelegateSignature(ESlateVisibility InVisibility);
    void ExecuteUbergraph_WBP_ReplayEditorMain(int32 EntryPoint);
    void NavigationKeyDownDispatcher__DelegateSignature(FKey Key);
};

#endif
