#ifndef UE4SS_SDK_Wuguan_Servant_AnimationBlueprint_Child_HPP
#define UE4SS_SDK_Wuguan_Servant_AnimationBlueprint_Child_HPP

class UWuguan_Servant_AnimationBlueprint_Child_C : public UWuguan_Character_AnimationBlueprint_C
{
};

#endif
