#ifndef UE4SS_SDK_Wuguan_BigGuy_AnimationBlueprint_Child_HPP
#define UE4SS_SDK_Wuguan_BigGuy_AnimationBlueprint_Child_HPP

class UWuguan_BigGuy_AnimationBlueprint_Child_C : public UWuguan_Character_AnimationBlueprint_C
{
};

#endif
