#ifndef UE4SS_SDK_Yang_ElbowSync_SynchronizedHitAction_HPP
#define UE4SS_SDK_Yang_ElbowSync_SynchronizedHitAction_HPP

class UYang_ElbowSync_SynchronizedHitAction_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
