#ifndef UE4SS_SDK_Yang_CrookedFoot_SynchronizedHitAction_HPP
#define UE4SS_SDK_Yang_CrookedFoot_SynchronizedHitAction_HPP

class UYang_CrookedFoot_SynchronizedHitAction_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
