#ifndef UE4SS_SDK_AttackThrowCancelAvailabilityOrderService_HPP
#define UE4SS_SDK_AttackThrowCancelAvailabilityOrderService_HPP

class UAttackThrowCancelAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
