#ifndef UE4SS_SDK_BP_AiCondition_TargetPerformedTakedownReaction_HPP
#define UE4SS_SDK_BP_AiCondition_TargetPerformedTakedownReaction_HPP

class UBP_AiCondition_TargetPerformedTakedownReaction_C : public UBP_AiCondition_TargetOrderPlayed_C
{
};

#endif
