#ifndef UE4SS_SDK_BP_AttackSyncVictimCheckTargetOrderService_HPP
#define UE4SS_SDK_BP_AttackSyncVictimCheckTargetOrderService_HPP

class UBP_AttackSyncVictimCheckTargetOrderService_C : public UBP_BaseTargetCheckOrderService_C
{
};

#endif
