#ifndef UE4SS_SDK_BP_AiCondition_TargetOrderPlayed_HPP
#define UE4SS_SDK_BP_AiCondition_TargetOrderPlayed_HPP

class UBP_AiCondition_TargetOrderPlayed_C : public UBP_AiCondition_TargetOrderState_C
{
};

#endif
