#ifndef UE4SS_SDK_BP_AttackEnvInstigatorCheckTargetOrderService_HPP
#define UE4SS_SDK_BP_AttackEnvInstigatorCheckTargetOrderService_HPP

class UBP_AttackEnvInstigatorCheckTargetOrderService_C : public UBP_BaseTargetCheckOrderService_C
{
};

#endif
