#ifndef UE4SS_SDK_BP_AiAction_WallJumpAttack_Vertical_HPP
#define UE4SS_SDK_BP_AiAction_WallJumpAttack_Vertical_HPP

class UBP_AiAction_WallJumpAttack_Vertical_C : public UBP_AiAction_WallJumpAttack_C
{
};

#endif
