#ifndef UE4SS_SDK_BP_AiCondition_IsTargetStructureBroken_HPP
#define UE4SS_SDK_BP_AiCondition_IsTargetStructureBroken_HPP

class UBP_AiCondition_IsTargetStructureBroken_C : public UComboAIConditionIsTargetFightingState
{
};

#endif
