#ifndef UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_FengJie_HPP
#define UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_FengJie_HPP

class UBP_FarMixerBlender_CombatLocked_Boss_FengJie_C : public UBP_FarMixerBlender_CombatLocked_Boss_C
{
};

#endif
