#ifndef UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_HPP
#define UE4SS_SDK_BP_FarMixerBlender_CombatLocked_Boss_HPP

class UBP_FarMixerBlender_CombatLocked_Boss_C : public UBP_FarMixerBlender_CombatLocked_C
{
};

#endif
