#ifndef UE4SS_SDK_BP_Hideout0MapPagedMenuCondition_HPP
#define UE4SS_SDK_BP_Hideout0MapPagedMenuCondition_HPP

class UBP_Hideout0MapPagedMenuCondition_C : public UBP_CurrentMapPagedMenuCondition_C
{
};

#endif
