#ifndef UE4SS_SDK_BP_Menu_Options_Feats_HPP
#define UE4SS_SDK_BP_Menu_Options_Feats_HPP

class UBP_Menu_Options_Feats_C : public UGameplayOptionsMenu
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UCanvasPanel* ActivatedCheats;
    class UHorizontalBox* Border_InputsnoAnim;
    class UBP_ActiveModifierBox_C* BP_ActiveModifierBox;
    class UBP_Menu_Popup_Validation_C* BP_Menu_Popup_Validation;
    class UTextBlock* BtnText;
    class UTextBlock* BtnText_1;
    class UTextBlock* BtnText_2;
    class UTextBlock* BtnText_3;
    class UTextBlock* BtnText_4;
    class UTextBlock* BtnText_5;
    class UTextBlock* BtnText_6;
    class USizeBox* DescriptionSizeBox;
    class UBP_Btn_Feat_C* DriverOutfit;
    class UBP_Btn_Feat_C* EnforcerOutfit;
    class UBP_Btn_Feat_C* FriendlyFireOnAvoid;
    class UBP_Btn_Feat_C* FullParryFajar;
    class UBP_Btn_Feat_C* FullParryJinfeng;
    class UBP_Btn_Feat_C* FullParryKuroki;
    class UBP_Btn_Feat_C* FullParrySean;
    class UBP_Btn_Feat_C* FullParryYang;
    class UBP_Btn_CheatCategory_Tab_C* General;
    class UVerticalBox* Global_VB_1;
    class UBP_Btn_Feat_C* H1DamageLess_1;
    class UBP_Btn_Feat_C* H1HighScoreHigh;
    class UBP_Btn_Feat_C* H1HighScoreLow;
    class UBP_Btn_Feat_C* H1HighScoreMiddle;
    class UBP_Btn_Feat_C* H1ScoreMult;
    class UBP_Btn_Feat_C* H1Sneak;
    class UBP_Btn_Feat_C* H1ThrowStrike;
    class UBP_Btn_Feat_C* H1TimeTrial;
    class UBP_Btn_Feat_C* H2ClubMaster;
    class UBP_Btn_Feat_C* H2DamageLess;
    class UBP_Btn_Feat_C* H2DJ;
    class UBP_Btn_Feat_C* H2HighScoreHigh;
    class UBP_Btn_Feat_C* H2HighScoreLow;
    class UBP_Btn_Feat_C* H2HighScoreMiddle;
    class UBP_Btn_Feat_C* H2ScoreMult;
    class UBP_Btn_Feat_C* H2TimeTrial;
    class UBP_Btn_Feat_C* H3Blade;
    class UBP_Btn_Feat_C* H3DamageLess;
    class UBP_Btn_Feat_C* H3HighScoreHigh;
    class UBP_Btn_Feat_C* H3HighScoreLow;
    class UBP_Btn_Feat_C* H3HighScoreMiddle;
    class UBP_Btn_Feat_C* H3Panels;
    class UBP_Btn_Feat_C* H3Pendulum;
    class UBP_Btn_Feat_C* H3ScoreMult;
    class UBP_Btn_Feat_C* H3TimeTrial;
    class UBP_Btn_Feat_C* H4Backfist;
    class UBP_Btn_Feat_C* H4DamageLess_1;
    class UBP_Btn_Feat_C* H4Elevator;
    class UBP_Btn_Feat_C* H4HighScoreHigh;
    class UBP_Btn_Feat_C* H4HighScoreLow;
    class UBP_Btn_Feat_C* H4HighScoreMiddle;
    class UBP_Btn_Feat_C* H4ScoreMult;
    class UBP_Btn_Feat_C* H4TimeTrial;
    class UBP_Btn_Feat_C* H4Trip;
    class UBP_Btn_Feat_C* H5Chef;
    class UBP_Btn_Feat_C* H5DamageLess;
    class UBP_Btn_Feat_C* H5HighScoreHigh;
    class UBP_Btn_Feat_C* H5HighScoreLow;
    class UBP_Btn_Feat_C* H5HighScoreMiddle;
    class UBP_Btn_Feat_C* H5ScoreMult;
    class UBP_Btn_Feat_C* H5TimeTrial;
    class UBP_Btn_Feat_C* H5Vanilla;
    class UBP_Btn_CheatCategory_Tab_C* Hideout1;
    class UVerticalBox* Hideout1_VB;
    class UBP_Btn_CheatCategory_Tab_C* Hideout2;
    class UVerticalBox* Hideout2_VB;
    class UBP_Btn_CheatCategory_Tab_C* Hideout3;
    class UVerticalBox* Hideout3_VB;
    class UBP_Btn_CheatCategory_Tab_C* Hideout4;
    class UVerticalBox* Hideout4_VB;
    class UBP_Btn_CheatCategory_Tab_C* Hideout5;
    class UVerticalBox* Hideout5_VB;
    class UBP_Btn_Feat_C* HighScoreTotalLow;
    class UBP_Btn_Feat_C* HighScoreTotalMiddle;
    class UImage* Icon;
    class UBP_Btn_InputTip_C* InputTip_Back;
    class UImage* LineLeft;
    class UImage* LineLeft_1;
    class UImage* LineLeft_2;
    class UImage* LineLeft_3;
    class UImage* LineLeft_4;
    class UImage* LineLeft_5;
    class UImage* LineRight;
    class UImage* LineRight_1;
    class UImage* LineRight_2;
    class UImage* LineRight_3;
    class UImage* LineRight_4;
    class UImage* LineRight_5;
    class UBP_Btn_Feat_C* LowAvoid;
    class UCanvasPanel* Popup;
    class UBP_Btn_Feat_C* ReplayEditor_Record;
    class UBP_Btn_Feat_C* ReplayEditor_Replay;
    class UBP_Btn_Feat_C* ScoreHoldMax;
    class UBP_Btn_Feat_C* ScoreIncreaseFast;
    class UBP_Btn_Feat_C* ScoreMaxFast;
    class UScrollBox* ScrollBoxCat0;
    class UScrollBox* ScrollBoxCat1;
    class UScrollBox* ScrollBoxCat2;
    class UScrollBox* ScrollBoxCat3;
    class UScrollBox* ScrollBoxCat4;
    class UScrollBox* ScrollBoxGlobal;
    class UBP_Btn_Feat_C* SkillsPerma;
    class UWidgetSwitcher* SwitcherFeats;
    class UBP_Btn_Feat_C* TrophyFocus;
    class UBP_Btn_Feat_C* TrophyMaxAge;
    class UBP_Btn_Feat_C* TrophyTimedTakedown;
    class UBP_Btn_Feat_C* TrophyWideStrike;
    class UBP_Btn_Feat_C* UnlockGoals;
    class UVerticalBox* VBCategories;
    class UBP_Btn_Feat_C* WingChunDarkOutfit;
    class UBP_Btn_Feat_C* WingChunLightOutfit;
    class UButtonUserWidget* FocusedCombo;
    bool AudioApplied;
    class UBP_Btn_SpinBox_C* FocusedOption;
    TMap<class FString, class FText> AudioLanguageMap;
    bool IsFocusScrollBar;
    TArray<class UWidget*> AllCheats;
    class UBP_Btn_SpinBox_Modifiers_C* SpinboxToUnlock;
    bool AAAAAAAAAAAAAAAA;
    TArray<EFocusCause> AllowedCategoryFocusCause;

    void InitializeFeatButtons();
    void FindButtonFromTagName(FString TagName, int32& Array Index, class UBP_Btn_Feat_C*& AsBP Btn Feat);
    void OnUpdateModeChange();
    void GetCurrentLevelHideoutIndex(int32& HideoutIndex);
    class UWidget* LoopFromBottomCategory(EUINavigation Navigation);
    class UWidget* LoopFromTopCategory(EUINavigation Navigation);
    void ClearChildrenCategoryGoals(class UVerticalBox* VerticalBox);
    void PopulateFeats();
    void ScrollToTop();
    void SortAllAchievedGoals();
    void SortAchievedGoals(class UVerticalBox* GoalsCategory);
    void SetDarkMode(bool IsDarkMode);
    void ResetCategoriesState();
    void FocusOnCategoryAtIndex(int32 Index);
    void FocusOnFirstElement(class UWidget* ParentCategory);
    void UpdateActivatedCheatsSumary();
    void UpdateCheatActivationOnValueChanged(float RatioFloat, FGameplayTag GameplayTag);
    bool BPE_OnBackButtonPressed();
    class UWidget* LoopFromBottom(EUINavigation Navigation);
    class UWidget* LoopFromTop(EUINavigation Navigation);
    void LoopCheatOptions(bool SetDefault);
    void Construct();
    void BndEvt__BP_Menu_Options_Cheat_Cat_Various_K2Node_ComponentBoundEvent_1_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Cheat_Cat_YourCharacter_K2Node_ComponentBoundEvent_3_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Ennemies_K2Node_ComponentBoundEvent_5_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Various_K2Node_ComponentBoundEvent_0_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_YourCharacter_K2Node_ComponentBoundEvent_2_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Cheat_Cat_Ennemies_K2Node_ComponentBoundEvent_4_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BPE_OnMenuTransitionIn(EMenuTransitions _eTransition, EMenuEnum _ePrevMenu);
    void BndEvt__BP_Menu_Options_Feats_Cat_K2Node_ComponentBoundEvent_6_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_Cat_K2Node_ComponentBoundEvent_7_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Feats_Cat_3_K2Node_ComponentBoundEvent_8_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_Cat_3_K2Node_ComponentBoundEvent_9_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BndEvt__BP_Menu_Options_Feats_Cat_0_K2Node_ComponentBoundEvent_10_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_Cat_1_K2Node_ComponentBoundEvent_11_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_Cat_2_K2Node_ComponentBoundEvent_12_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_Cat_K2Node_ComponentBoundEvent_13_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_Cat_3_K2Node_ComponentBoundEvent_14_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_General_K2Node_ComponentBoundEvent_16_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_General_K2Node_ComponentBoundEvent_15_ButtonUserWidgetDelegate__DelegateSignature(class UButtonUserWidget* _button, EFocusCause _eCause);
    void BndEvt__BP_Menu_Options_Feats_General_K2Node_ComponentBoundEvent_17_ButtonUserWidgetClickDelegate__DelegateSignature(class UButtonUserWidget* _button, bool _bWithMouse);
    void BPE_OnUIInputModeChanged(EUIInputModes _eMode, bool _bInit);
    void LaunchBackSequence();
    void HandleMenuRequest(FString InArguments);
    void BPE_GiveFocus();
    void ExecuteUbergraph_BP_Menu_Options_Feats(int32 EntryPoint);
};

#endif
