#ifndef UE4SS_SDK_BP_RagingBullLDCollisionOrderService_IgnoreTarget_HPP
#define UE4SS_SDK_BP_RagingBullLDCollisionOrderService_IgnoreTarget_HPP

class UBP_RagingBullLDCollisionOrderService_IgnoreTarget_C : public UBP_RagingBullLDCollisionOrderService_C
{
};

#endif
