#ifndef UE4SS_SDK_BP_RagingBullHitOrderService_Entry_HPP
#define UE4SS_SDK_BP_RagingBullHitOrderService_Entry_HPP

class UBP_RagingBullHitOrderService_Entry_C : public UBP_RagingBullHitOrderService_C
{
};

#endif
