#ifndef UE4SS_SDK_BP_ShrineModifierCalculation_StructureUp_HPP
#define UE4SS_SDK_BP_ShrineModifierCalculation_StructureUp_HPP

class UBP_ShrineModifierCalculation_StructureUp_C : public UBP_ShrineModifierCalculation_C
{
};

#endif
