#ifndef UE4SS_SDK_BP_ShrineModifierCalculation_WeaponDamage_HPP
#define UE4SS_SDK_BP_ShrineModifierCalculation_WeaponDamage_HPP

class UBP_ShrineModifierCalculation_WeaponDamage_C : public UBP_ShrineModifierCalculation_C
{
};

#endif
