#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_FocusRegain_Lvl3_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_FocusRegain_Lvl3_HPP

class UBP_ShrineGameplayEffect_FocusRegain_Lvl3_C : public UBP_ShrineGameplayEffect_FocusRegain_Lvl1_C
{
};

#endif
