#ifndef UE4SS_SDK_BP_ShrineModifierCalculation_FocusGain_HPP
#define UE4SS_SDK_BP_ShrineModifierCalculation_FocusGain_HPP

class UBP_ShrineModifierCalculation_FocusGain_C : public UBP_ShrineModifierCalculation_C
{
};

#endif
