#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_AvoidGain_Lvl2_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_AvoidGain_Lvl2_HPP

class UBP_ShrineGameplayEffect_AvoidGain_Lvl2_C : public UBP_ShrineGameplayEffect_AvoidGain_Lvl1_C
{
};

#endif
