#ifndef UE4SS_SDK_BP_ShrineModifierCalculation_ParryIncreaseImpact_HPP
#define UE4SS_SDK_BP_ShrineModifierCalculation_ParryIncreaseImpact_HPP

class UBP_ShrineModifierCalculation_ParryIncreaseImpact_C : public UBP_ShrineModifierCalculation_C
{
};

#endif
