#ifndef UE4SS_SDK_BP_ThrowableData_Unbreakable_Blade_HPP
#define UE4SS_SDK_BP_ThrowableData_Unbreakable_Blade_HPP

class UBP_ThrowableData_Unbreakable_Blade_C : public UBP_ThrowableData_Weapon_BladeFamily_C
{
};

#endif
