#ifndef UE4SS_SDK_BP_TE_DirectionalWeightEval_Throw_HPP
#define UE4SS_SDK_BP_TE_DirectionalWeightEval_Throw_HPP

class UBP_TE_DirectionalWeightEval_Throw_C : public UTE_DirectionalWeightEvaluation
{
};

#endif
