#ifndef UE4SS_SDK_BP_TE_DirectionalWeightEval_RushAttack_HPP
#define UE4SS_SDK_BP_TE_DirectionalWeightEval_RushAttack_HPP

class UBP_TE_DirectionalWeightEval_RushAttack_C : public UTE_DirectionalWeightEvaluation
{
};

#endif
