#ifndef UE4SS_SDK_BP_TransitionAnimRequest_FireDisciple_HPP
#define UE4SS_SDK_BP_TransitionAnimRequest_FireDisciple_HPP

class UBP_TransitionAnimRequest_FireDisciple_C : public UBP_TransitionAnimRequest_AI_C
{
};

#endif
