#ifndef UE4SS_SDK_BP_VitalPointCheckCondition_BladeDamage_HPP
#define UE4SS_SDK_BP_VitalPointCheckCondition_BladeDamage_HPP

class UBP_VitalPointCheckCondition_BladeDamage_C : public UBP_EquippedWeaponVitalPointCondition_C
{
};

#endif
