#ifndef UE4SS_SDK_BP_VitalPointCheckConditionPlexus_HPP
#define UE4SS_SDK_BP_VitalPointCheckConditionPlexus_HPP

class UBP_VitalPointCheckConditionPlexus_C : public UBP_VitalPointCheckConditionBase_C
{
};

#endif
