#ifndef UE4SS_SDK_BP_VitalPointCheckConditionBelly_HPP
#define UE4SS_SDK_BP_VitalPointCheckConditionBelly_HPP

class UBP_VitalPointCheckConditionBelly_C : public UBP_VitalPointCheckConditionBase_C
{
};

#endif
