#ifndef UE4SS_SDK_BP_VitalPointCheckCondition_StaffAoe_HPP
#define UE4SS_SDK_BP_VitalPointCheckCondition_StaffAoe_HPP

class UBP_VitalPointCheckCondition_StaffAoe_C : public UBP_EquippedWeaponVitalPointCondition_C
{
};

#endif
