#ifndef UE4SS_SDK_BP_Weapon_MCStaff_DefenseAnimRequest_HPP
#define UE4SS_SDK_BP_Weapon_MCStaff_DefenseAnimRequest_HPP

class UBP_Weapon_MCStaff_DefenseAnimRequest_C : public UBP_DefenseAnimRequest_C
{
};

#endif
