#ifndef UE4SS_SDK_Cheat_DoubleDamageReceivedGameplayEffect_HPP
#define UE4SS_SDK_Cheat_DoubleDamageReceivedGameplayEffect_HPP

class UCheat_DoubleDamageReceivedGameplayEffect_C : public UGameplayEffect
{
};

#endif
