#ifndef UE4SS_SDK_DodgeActionRecoveryAvailabilityOrderService_HPP
#define UE4SS_SDK_DodgeActionRecoveryAvailabilityOrderService_HPP

class UDodgeActionRecoveryAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
