#ifndef UE4SS_SDK_FallInterruptAvailablityOrderService_HPP
#define UE4SS_SDK_FallInterruptAvailablityOrderService_HPP

class UFallInterruptAvailablityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
