#ifndef UE4SS_SDK_FarGrabSynchronizedAttackHitActionLauncher_HPP
#define UE4SS_SDK_FarGrabSynchronizedAttackHitActionLauncher_HPP

class UFarGrabSynchronizedAttackHitActionLauncher_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
