#ifndef UE4SS_SDK_GrabTakedownSynchronizedAttackHitActionLauncher_HPP
#define UE4SS_SDK_GrabTakedownSynchronizedAttackHitActionLauncher_HPP

class UGrabTakedownSynchronizedAttackHitActionLauncher_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
