#ifndef UE4SS_SDK_HittedCancelAvailabilityOrderService_HPP
#define UE4SS_SDK_HittedCancelAvailabilityOrderService_HPP

class UHittedCancelAvailabilityOrderService_C : public UAvailabilityLayerOrderService
{
};

#endif
