#ifndef UE4SS_SDK_HittedPushUntargettableOrderService_HPP
#define UE4SS_SDK_HittedPushUntargettableOrderService_HPP

class UHittedPushUntargettableOrderService_C : public UUntargettableOrderService
{
};

#endif
