#ifndef UE4SS_SDK_KnockdownHitGetUpRedirectOrderService_HPP
#define UE4SS_SDK_KnockdownHitGetUpRedirectOrderService_HPP

class UKnockdownHitGetUpRedirectOrderService_C : public URedirectToTargetOrderService
{
};

#endif
