#ifndef UE4SS_SDK_MainChar_ElbowSyncBT_SynchronizedHitAction_HPP
#define UE4SS_SDK_MainChar_ElbowSyncBT_SynchronizedHitAction_HPP

class UMainChar_ElbowSyncBT_SynchronizedHitAction_C : public UMainChar_ElbowSync_SynchronizedHitAction_C
{
};

#endif
