#ifndef UE4SS_SDK_MainChar_Staff_HoldRanged_SynchronizedHitAction_HPP
#define UE4SS_SDK_MainChar_Staff_HoldRanged_SynchronizedHitAction_HPP

class UMainChar_Staff_HoldRanged_SynchronizedHitAction_C : public UBP_SynchronizedAttacksHitAction_C
{
};

#endif
