#ifndef UE4SS_SDK_OrderHittedGeneric_HittedOrderService_SettableHitbox_HPP
#define UE4SS_SDK_OrderHittedGeneric_HittedOrderService_SettableHitbox_HPP

class UOrderHittedGeneric_HittedOrderService_SettableHitbox_C : public UHittedOrderService
{

    FAnimContainer BPE_GetFightingStateLoopAnim(const FBPOrderServiceInstance& _orderServiceInstance);
};

#endif
