#ifndef UE4SS_SDK_BP_AiAction_Kuroki_RainIntermediateDashRight_HPP
#define UE4SS_SDK_BP_AiAction_Kuroki_RainIntermediateDashRight_HPP

class UBP_AiAction_Kuroki_RainIntermediateDashRight_C : public UBP_AiAction_Kuroki_RainIntermediateDashLeft_C
{
}; // Size: 0x428

#endif
