#ifndef UE4SS_SDK_BP_Fengjie_ArchetypeDB_Training_Phase1_ShortRange_HPP
#define UE4SS_SDK_BP_Fengjie_ArchetypeDB_Training_Phase1_ShortRange_HPP

class UBP_Fengjie_ArchetypeDB_Training_Phase1_ShortRange_C : public UBP_Fengjie_Phase1_ShortRange_ArchetypeDB_C
{
}; // Size: 0x6F9

#endif
