#ifndef UE4SS_SDK_BP_Kuroki_P2_ArchetypeDB_ShiroizuRanged_Arena_HPP
#define UE4SS_SDK_BP_Kuroki_P2_ArchetypeDB_ShiroizuRanged_Arena_HPP

class UBP_Kuroki_P2_ArchetypeDB_ShiroizuRanged_Arena_C : public UBP_Kuroki_P2_ArchetypeDB_ShiroizuMelee_Arena_C
{
}; // Size: 0x6F9

#endif
