#ifndef UE4SS_SDK_BP_Kuroki_ArchetypeDB_Training_Phase2_Ranged_HPP
#define UE4SS_SDK_BP_Kuroki_ArchetypeDB_Training_Phase2_Ranged_HPP

class UBP_Kuroki_ArchetypeDB_Training_Phase2_Ranged_C : public UBP_Kuroki_P2_ArchetypeDB_ShiroizuRanged_C
{
}; // Size: 0x6F9

#endif
