#ifndef UE4SS_SDK_BP_RagingBullRedirectToTrackedTargetOrderService_HPP
#define UE4SS_SDK_BP_RagingBullRedirectToTrackedTargetOrderService_HPP

class UBP_RagingBullRedirectToTrackedTargetOrderService_C : public URagingBullRedirectToTrackedTargetOrderService
{
}; // Size: 0x48

#endif
