#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_HealthGainOnTakedown_Lv2_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_HealthGainOnTakedown_Lv2_HPP

class UBP_ShrineGameplayEffect_HealthGainOnTakedown_Lv2_C : public UBP_ShrineGameplayEffect_HealthGainOnTakedown_Lv1_C
{
}; // Size: 0x7F8

#endif
