#ifndef UE4SS_SDK_BP_DynamicAccessory_MainChar_W_GrandMaster_Hat_HPP
#define UE4SS_SDK_BP_DynamicAccessory_MainChar_W_GrandMaster_Hat_HPP

class ABP_DynamicAccessory_MainChar_W_GrandMaster_Hat_C : public ABP_DynamicAccessory_MainChar_M_GrandMaster_Hat_C
{
}; // Size: 0x308

#endif
