#ifndef UE4SS_SDK_BP_ShrineGameplayEffect_HealthGainOnTakedown_Lv3_HPP
#define UE4SS_SDK_BP_ShrineGameplayEffect_HealthGainOnTakedown_Lv3_HPP

class UBP_ShrineGameplayEffect_HealthGainOnTakedown_Lv3_C : public UBP_ShrineGameplayEffect_HealthGainOnTakedown_Lv1_C
{
}; // Size: 0x7F8

#endif
