#ifndef UE4SS_SDK_Cheat_TripleDamageMultiplierReceivedGameplayEffect_HPP
#define UE4SS_SDK_Cheat_TripleDamageMultiplierReceivedGameplayEffect_HPP

class UCheat_TripleDamageMultiplierReceivedGameplayEffect_C : public UCheat_DamageMultiplierReceivedGameplayEffect_C
{
}; // Size: 0x7F8

#endif
