#ifndef UE4SS_SDK_Knee_Smash_SynchronizedAttackHitActionLauncher_Hard_HPP
#define UE4SS_SDK_Knee_Smash_SynchronizedAttackHitActionLauncher_Hard_HPP

class UKnee_Smash_SynchronizedAttackHitActionLauncher_Hard_C : public UBP_SynchronizedAttacksHitAction_C
{
}; // Size: 0x2A8

#endif
