#ifndef UE4SS_SDK_MainChar_Special_GrabTakedown_SynchronizedHitAction_HPP
#define UE4SS_SDK_MainChar_Special_GrabTakedown_SynchronizedHitAction_HPP

class UMainChar_Special_GrabTakedown_SynchronizedHitAction_C : public UBP_SynchronizedAttacksHitAction_C
{
}; // Size: 0x2A8

#endif
