#ifndef UE4SS_SDK_Wuguan_Character_AnimationBlueprint_HPP
#define UE4SS_SDK_Wuguan_Character_AnimationBlueprint_HPP

class UWuguan_Character_AnimationBlueprint_C : public UPlayerAnim
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x2080 (size: 0x8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_29;                           // 0x2088 (size: 0x28)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_10;                                 // 0x20B0 (size: 0x108)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_28;                           // 0x21B8 (size: 0x28)
    FAnimNode_LinkedAnimGraph AnimGraphNode_SubInstance_2;                            // 0x21E0 (size: 0xA0)
    FSCAnimNode_VariableWeightBlender SCAnimGraphNode_VariableWeightBlender_5;        // 0x2280 (size: 0x98)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_12;                         // 0x2318 (size: 0x158)
    FSCAnimNode_VariableWeightBlender SCAnimGraphNode_VariableWeightBlender_4;        // 0x2470 (size: 0x98)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_6;                        // 0x2508 (size: 0xA0)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_5;                        // 0x25A8 (size: 0xA0)
    FSCAnimNode_VariableWeightBlender SCAnimGraphNode_VariableWeightBlender_3;        // 0x2648 (size: 0x98)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_27;                           // 0x26E0 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_26;                           // 0x2708 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_25;                           // 0x2730 (size: 0x28)
    FAnimNode_Slot AnimGraphNode_Slot_1;                                              // 0x2758 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot;                                                // 0x27A0 (size: 0x48)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend_6;                                // 0x27E8 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_24;                           // 0x28B0 (size: 0x28)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend_5;                                // 0x28D8 (size: 0xC8)
    FSCAnimNode_VariableWeightBlender SCAnimGraphNode_VariableWeightBlender_2;        // 0x29A0 (size: 0x98)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_4;     // 0x2A38 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_9;                                  // 0x2A58 (size: 0x108)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_4;     // 0x2B60 (size: 0x20)
    FSCAnimNode_VariableWeightBlender SCAnimGraphNode_VariableWeightBlender_1;        // 0x2B80 (size: 0x98)
    FSCAnimNode_ComputeVariableWeight SCAnimGraphNode_ComputeVariableWeight;          // 0x2C18 (size: 0x20)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_11;                         // 0x2C38 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_23;                           // 0x2D90 (size: 0x28)
    FSCAnimNode_VariableWeightBlender SCAnimGraphNode_VariableWeightBlender;          // 0x2DB8 (size: 0x98)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_22;                           // 0x2E50 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_77;                                 // 0x2E78 (size: 0xB8)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_10;                         // 0x2F30 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_21;                           // 0x3088 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_20;                           // 0x30B0 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_19;                           // 0x30D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_192;                    // 0x3100 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_191;                    // 0x3128 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_190;                    // 0x3150 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_189;                    // 0x3178 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_188;                    // 0x31A0 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_76;                                 // 0x31C8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_95;                               // 0x3280 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_75;                                 // 0x32B0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_94;                               // 0x3368 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_187;                    // 0x3398 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_74;                                 // 0x33C0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_93;                               // 0x3478 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_24;                             // 0x34A8 (size: 0xB0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_186;                    // 0x3558 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_185;                    // 0x3580 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_184;                    // 0x35A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_183;                    // 0x35D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_182;                    // 0x35F8 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_73;                                 // 0x3620 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_92;                               // 0x36D8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_72;                                 // 0x3708 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_91;                               // 0x37C0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_181;                    // 0x37F0 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_71;                                 // 0x3818 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_90;                               // 0x38D0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_23;                             // 0x3900 (size: 0xB0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_180;                    // 0x39B0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_179;                    // 0x39D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_178;                    // 0x3A00 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_177;                    // 0x3A28 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_176;                    // 0x3A50 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_70;                                 // 0x3A78 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_89;                               // 0x3B30 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_69;                                 // 0x3B60 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_88;                               // 0x3C18 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_175;                    // 0x3C48 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_68;                                 // 0x3C70 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_87;                               // 0x3D28 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_22;                             // 0x3D58 (size: 0xB0)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_9;                          // 0x3E08 (size: 0x158)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend_4;                                // 0x3F60 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_18;                           // 0x4028 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_17;                           // 0x4050 (size: 0x28)
    FSCAnimNode_SaveBoneTransformByName SCAnimGraphNode_SaveBoneTransformByName_2;    // 0x4078 (size: 0x58)
    FSCAnimNode_SaveBoneTransformByName SCAnimGraphNode_SaveBoneTransformByName_1;    // 0x40D0 (size: 0x58)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_8;                          // 0x4128 (size: 0x158)
    FAnimNode_BlendListByInt AnimGraphNode_BlendListByInt_1;                          // 0x4280 (size: 0xA0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_16;                           // 0x4320 (size: 0x28)
    FSCAnimNode_RotationOffsetBlendSpace SCAnimGraphNode_RotationOffsetBlendSpace_1;  // 0x4348 (size: 0x1A8)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_3;     // 0x44F0 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_8;                                  // 0x4510 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_7;                                  // 0x4618 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_6;                                  // 0x4720 (size: 0x108)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_15;                           // 0x4828 (size: 0x28)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_4;                        // 0x4850 (size: 0xA0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_14;                           // 0x48F0 (size: 0x28)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_5;                                  // 0x4918 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_4;                                  // 0x4A20 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_3;                                  // 0x4B28 (size: 0x108)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_3;     // 0x4C30 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_13;                           // 0x4C50 (size: 0x28)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_15;                       // 0x4C78 (size: 0xB0)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_2;                                  // 0x4D28 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_1;                                  // 0x4E30 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;                                    // 0x4F38 (size: 0x108)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;     // 0x5040 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_12;                           // 0x5060 (size: 0x28)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;     // 0x5088 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_11;                           // 0x50A8 (size: 0x28)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;     // 0x50D0 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_10;                           // 0x50F0 (size: 0x28)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;     // 0x5118 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_9;                            // 0x5138 (size: 0x28)
    FSCAnimNode_RotationOffsetBlendSpace SCAnimGraphNode_RotationOffsetBlendSpace;    // 0x5160 (size: 0x1A8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_8;                            // 0x5308 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_7;                          // 0x5330 (size: 0x158)
    FAnimNode_PoseSnapshot AnimGraphNode_PoseSnapshot_2;                              // 0x5488 (size: 0x90)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_3;                        // 0x5518 (size: 0xA0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_7;                            // 0x55B8 (size: 0x28)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_2;                        // 0x55E0 (size: 0xA0)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_6;                          // 0x5680 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_6;                            // 0x57D8 (size: 0x28)
    FAnimNode_PoseBlendNode AnimGraphNode_PoseBlendNode;                              // 0x5800 (size: 0xB8)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_174;                    // 0x58B8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_173;                    // 0x58E0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_172;                    // 0x5908 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_171;                    // 0x5930 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_170;                    // 0x5958 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_169;                    // 0x5980 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_168;                    // 0x59A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_167;                    // 0x59D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_166;                    // 0x59F8 (size: 0x28)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_14;                       // 0x5A20 (size: 0xB0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_20;                     // 0x5AD0 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_19;                     // 0x5BE0 (size: 0x110)
    FAnimNode_StateResult AnimGraphNode_StateResult_86;                               // 0x5CF0 (size: 0x30)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_13;                       // 0x5D20 (size: 0xB0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_18;                     // 0x5DD0 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_17;                     // 0x5EE0 (size: 0x110)
    FAnimNode_StateResult AnimGraphNode_StateResult_85;                               // 0x5FF0 (size: 0x30)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_12;                       // 0x6020 (size: 0xB0)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_11;                       // 0x60D0 (size: 0xB0)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_10;                       // 0x6180 (size: 0xB0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_16;                     // 0x6230 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_15;                     // 0x6340 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_14;                     // 0x6450 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_13;                     // 0x6560 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_12;                     // 0x6670 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_11;                     // 0x6780 (size: 0x110)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_9;                        // 0x6890 (size: 0xB0)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_1;                      // 0x6940 (size: 0xC0)
    FAnimNode_StateResult AnimGraphNode_StateResult_84;                               // 0x6A00 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_67;                                 // 0x6A30 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_83;                               // 0x6AE8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_66;                                 // 0x6B18 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_65;                                 // 0x6BD0 (size: 0xB8)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_8;                        // 0x6C88 (size: 0xB0)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_64;                                 // 0x6D38 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_63;                                 // 0x6DF0 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_62;                                 // 0x6EA8 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_61;                                 // 0x6F60 (size: 0xB8)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_7;                        // 0x7018 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_82;                               // 0x70C8 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_165;                    // 0x70F8 (size: 0x28)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_21;                             // 0x7120 (size: 0xB0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_5;                            // 0x71D0 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_5;                          // 0x71F8 (size: 0x158)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_164;                    // 0x7350 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_163;                    // 0x7378 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_162;                    // 0x73A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_161;                    // 0x73C8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_160;                    // 0x73F0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_159;                    // 0x7418 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_158;                    // 0x7440 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_157;                    // 0x7468 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_156;                    // 0x7490 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_155;                    // 0x74B8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_154;                    // 0x74E0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_153;                    // 0x7508 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_152;                    // 0x7530 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_151;                    // 0x7558 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_150;                    // 0x7580 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_149;                    // 0x75A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_148;                    // 0x75D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_147;                    // 0x75F8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_146;                    // 0x7620 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_145;                    // 0x7648 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_144;                    // 0x7670 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_143;                    // 0x7698 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_142;                    // 0x76C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_141;                    // 0x76E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_140;                    // 0x7710 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_139;                    // 0x7738 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_138;                    // 0x7760 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_137;                    // 0x7788 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_136;                    // 0x77B0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_135;                    // 0x77D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_134;                    // 0x7800 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_133;                    // 0x7828 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_132;                    // 0x7850 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_131;                    // 0x7878 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_130;                    // 0x78A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_129;                    // 0x78C8 (size: 0x28)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_14;   // 0x78F0 (size: 0xD0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_128;                    // 0x79C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_127;                    // 0x79E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_126;                    // 0x7A10 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_125;                    // 0x7A38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_124;                    // 0x7A60 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_123;                    // 0x7A88 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_60;                                 // 0x7AB0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_81;                               // 0x7B68 (size: 0x30)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_10;                     // 0x7B98 (size: 0x110)
    FAnimNode_StateResult AnimGraphNode_StateResult_80;                               // 0x7CA8 (size: 0x30)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_9;                      // 0x7CD8 (size: 0x110)
    FAnimNode_StateResult AnimGraphNode_StateResult_79;                               // 0x7DE8 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_20;                             // 0x7E18 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_78;                               // 0x7EC8 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_122;                    // 0x7EF8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_121;                    // 0x7F20 (size: 0x28)
    FAnimNode_LinkedAnimGraph AnimGraphNode_LinkedAnimGraph_4;                        // 0x7F48 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_77;                               // 0x7FE8 (size: 0x30)
    FAnimNode_StateResult AnimGraphNode_StateResult_76;                               // 0x8018 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_19;                             // 0x8048 (size: 0xB0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;                            // 0x80F8 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_4;                          // 0x8120 (size: 0x158)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_13;   // 0x8278 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_75;                               // 0x8348 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_120;                    // 0x8378 (size: 0x28)
    FAnimNode_LinkedAnimGraph AnimGraphNode_LinkedAnimGraph_3;                        // 0x83A0 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_74;                               // 0x8440 (size: 0x30)
    FAnimNode_StateResult AnimGraphNode_StateResult_73;                               // 0x8470 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_18;                             // 0x84A0 (size: 0xB0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;                            // 0x8550 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_3;                          // 0x8578 (size: 0x158)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_12;   // 0x86D0 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_72;                               // 0x87A0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_119;                    // 0x87D0 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_71;                               // 0x87F8 (size: 0x30)
    FAnimNode_LinkedAnimGraph AnimGraphNode_LinkedAnimGraph_2;                        // 0x8828 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_70;                               // 0x88C8 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_17;                             // 0x88F8 (size: 0xB0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;                            // 0x89A8 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_2;                          // 0x89D0 (size: 0x158)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_11;   // 0x8B28 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_69;                               // 0x8BF8 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_118;                    // 0x8C28 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_117;                    // 0x8C50 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_68;                               // 0x8C78 (size: 0x30)
    FAnimNode_LinkedAnimGraph AnimGraphNode_SubInstance_1;                            // 0x8CA8 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_67;                               // 0x8D48 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_16;                             // 0x8D78 (size: 0xB0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;                            // 0x8E28 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;                          // 0x8E50 (size: 0x158)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_10;   // 0x8FA8 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_66;                               // 0x9078 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_59;                                 // 0x90A8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_65;                               // 0x9160 (size: 0x30)
    FAnimNode_PoseSnapshot AnimGraphNode_PoseSnapshot_1;                              // 0x9190 (size: 0x90)
    FAnimNode_StateResult AnimGraphNode_StateResult_64;                               // 0x9220 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_58;                                 // 0x9250 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_63;                               // 0x9308 (size: 0x30)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_9;    // 0x9338 (size: 0xD0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_116;                    // 0x9408 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_115;                    // 0x9430 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_114;                    // 0x9458 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_113;                    // 0x9480 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_112;                    // 0x94A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_111;                    // 0x94D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_110;                    // 0x94F8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_109;                    // 0x9520 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_108;                    // 0x9548 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_107;                    // 0x9570 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_106;                    // 0x9598 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_105;                    // 0x95C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_104;                    // 0x95E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_103;                    // 0x9610 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_102;                    // 0x9638 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_57;                                 // 0x9660 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_62;                               // 0x9718 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_56;                                 // 0x9748 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_61;                               // 0x9800 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_55;                                 // 0x9830 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_60;                               // 0x98E8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_54;                                 // 0x9918 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_59;                               // 0x99D0 (size: 0x30)
    FAnimNode_LinkedAnimGraph AnimGraphNode_LinkedAnimGraph_1;                        // 0x9A00 (size: 0xA0)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_53;                                 // 0x9AA0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_58;                               // 0x9B58 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_15;                             // 0x9B88 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_57;                               // 0x9C38 (size: 0x30)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_8;    // 0x9C68 (size: 0xD0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_101;                    // 0x9D38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_100;                    // 0x9D60 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_99;                     // 0x9D88 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_98;                     // 0x9DB0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_97;                     // 0x9DD8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_96;                     // 0x9E00 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_95;                     // 0x9E28 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_94;                     // 0x9E50 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_93;                     // 0x9E78 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_52;                                 // 0x9EA0 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_51;                                 // 0x9F58 (size: 0xB8)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend_3;                                // 0xA010 (size: 0xC8)
    FAnimNode_StateResult AnimGraphNode_StateResult_56;                               // 0xA0D8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_50;                                 // 0xA108 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_49;                                 // 0xA1C0 (size: 0xB8)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend_2;                                // 0xA278 (size: 0xC8)
    FAnimNode_StateResult AnimGraphNode_StateResult_55;                               // 0xA340 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_48;                                 // 0xA370 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_47;                                 // 0xA428 (size: 0xB8)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend_1;                                // 0xA4E0 (size: 0xC8)
    FAnimNode_StateResult AnimGraphNode_StateResult_54;                               // 0xA5A8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_46;                                 // 0xA5D8 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_45;                                 // 0xA690 (size: 0xB8)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend;                                  // 0xA748 (size: 0xC8)
    FAnimNode_StateResult AnimGraphNode_StateResult_53;                               // 0xA810 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_92;                     // 0xA840 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_44;                                 // 0xA868 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_52;                               // 0xA920 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_14;                             // 0xA950 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_51;                               // 0xAA00 (size: 0x30)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;                              // 0xAA30 (size: 0x28)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;                            // 0xAA58 (size: 0x158)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_7;    // 0xABB0 (size: 0xD0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_91;                     // 0xAC80 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_90;                     // 0xACA8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_89;                     // 0xACD0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_88;                     // 0xACF8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_87;                     // 0xAD20 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_86;                     // 0xAD48 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_43;                                 // 0xAD70 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_50;                               // 0xAE28 (size: 0x30)
    FAnimNode_LinkedAnimGraph AnimGraphNode_LinkedAnimGraph;                          // 0xAE58 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_49;                               // 0xAEF8 (size: 0x30)
    FAnimNode_LinkedAnimGraph AnimGraphNode_SubInstance;                              // 0xAF28 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_48;                               // 0xAFC8 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_13;                             // 0xAFF8 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_47;                               // 0xB0A8 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_85;                     // 0xB0D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_84;                     // 0xB100 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_83;                     // 0xB128 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_82;                     // 0xB150 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_81;                     // 0xB178 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_42;                                 // 0xB1A0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_46;                               // 0xB258 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_41;                                 // 0xB288 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_45;                               // 0xB340 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_80;                     // 0xB370 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_40;                                 // 0xB398 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_44;                               // 0xB450 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_12;                             // 0xB480 (size: 0xB0)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_6;    // 0xB530 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_43;                               // 0xB600 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_79;                     // 0xB630 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_78;                     // 0xB658 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_77;                     // 0xB680 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_76;                     // 0xB6A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_75;                     // 0xB6D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_74;                     // 0xB6F8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_73;                     // 0xB720 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_72;                     // 0xB748 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_71;                     // 0xB770 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_70;                     // 0xB798 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_39;                                 // 0xB7C0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_42;                               // 0xB878 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_69;                     // 0xB8A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_68;                     // 0xB8D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_67;                     // 0xB8F8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_66;                     // 0xB920 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_65;                     // 0xB948 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_64;                     // 0xB970 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_63;                     // 0xB998 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_62;                     // 0xB9C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_61;                     // 0xB9E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_60;                     // 0xBA10 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_59;                     // 0xBA38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_58;                     // 0xBA60 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_57;                     // 0xBA88 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_56;                     // 0xBAB0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_55;                     // 0xBAD8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_54;                     // 0xBB00 (size: 0x28)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_5;    // 0xBB28 (size: 0xD0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_53;                     // 0xBBF8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_52;                     // 0xBC20 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_51;                     // 0xBC48 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_50;                     // 0xBC70 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_49;                     // 0xBC98 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_48;                     // 0xBCC0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_47;                     // 0xBCE8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_46;                     // 0xBD10 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_45;                     // 0xBD38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_44;                     // 0xBD60 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_43;                     // 0xBD88 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_42;                     // 0xBDB0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_41;                     // 0xBDD8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_40;                     // 0xBE00 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_39;                     // 0xBE28 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_38;                     // 0xBE50 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_37;                     // 0xBE78 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_36;                     // 0xBEA0 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_38;                                 // 0xBEC8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_41;                               // 0xBF80 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_37;                                 // 0xBFB0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_40;                               // 0xC068 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_35;                     // 0xC098 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_36;                                 // 0xC0C0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_39;                               // 0xC178 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_11;                             // 0xC1A8 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_38;                               // 0xC258 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_34;                     // 0xC288 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_33;                     // 0xC2B0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_32;                     // 0xC2D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_31;                     // 0xC300 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_30;                     // 0xC328 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_35;                                 // 0xC350 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_37;                               // 0xC408 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_34;                                 // 0xC438 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_36;                               // 0xC4F0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_29;                     // 0xC520 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_33;                                 // 0xC548 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_35;                               // 0xC600 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_10;                             // 0xC630 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_34;                               // 0xC6E0 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_32;                                 // 0xC710 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_33;                               // 0xC7C8 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_28;                     // 0xC7F8 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_31;                                 // 0xC820 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_32;                               // 0xC8D8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_30;                                 // 0xC908 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_31;                               // 0xC9C0 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_29;                                 // 0xC9F0 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_30;                               // 0xCAA8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_28;                                 // 0xCAD8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_29;                               // 0xCB90 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_27;                     // 0xCBC0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_26;                     // 0xCBE8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_25;                     // 0xCC10 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_24;                     // 0xCC38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_23;                     // 0xCC60 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_27;                                 // 0xCC88 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_28;                               // 0xCD40 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_26;                                 // 0xCD70 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_27;                               // 0xCE28 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_22;                     // 0xCE58 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_25;                                 // 0xCE80 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_26;                               // 0xCF38 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_9;                              // 0xCF68 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_25;                               // 0xD018 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_21;                     // 0xD048 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_20;                     // 0xD070 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_19;                     // 0xD098 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_18;                     // 0xD0C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_17;                     // 0xD0E8 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_24;                                 // 0xD110 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_24;                               // 0xD1C8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_23;                                 // 0xD1F8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_23;                               // 0xD2B0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_16;                     // 0xD2E0 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_22;                                 // 0xD308 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_22;                               // 0xD3C0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_8;                              // 0xD3F0 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_21;                               // 0xD4A0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_15;                     // 0xD4D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_14;                     // 0xD4F8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;                     // 0xD520 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;                     // 0xD548 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;                     // 0xD570 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_21;                                 // 0xD598 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_20;                               // 0xD650 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_20;                                 // 0xD680 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_19;                               // 0xD738 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;                     // 0xD768 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_19;                                 // 0xD790 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_18;                               // 0xD848 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_7;                              // 0xD878 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_17;                               // 0xD928 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_6;                              // 0xD958 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_16;                               // 0xDA08 (size: 0x30)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_6;                        // 0xDA38 (size: 0xB0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_8;                      // 0xDAE8 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_7;                      // 0xDBF8 (size: 0x110)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_4;    // 0xDD08 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_15;                               // 0xDDD8 (size: 0x30)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_5;                        // 0xDE08 (size: 0xB0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_6;                      // 0xDEB8 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_5;                      // 0xDFC8 (size: 0x110)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_3;    // 0xE0D8 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_14;                               // 0xE1A8 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;                      // 0xE1D8 (size: 0x28)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_4;                        // 0xE200 (size: 0xB0)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_3;                        // 0xE2B0 (size: 0xB0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_4;                      // 0xE360 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_3;                      // 0xE470 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_2;                      // 0xE580 (size: 0x110)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace_1;                      // 0xE690 (size: 0x110)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_2;    // 0xE7A0 (size: 0xD0)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;                        // 0xE870 (size: 0xA0)
    FAnimNode_StateResult AnimGraphNode_StateResult_13;                               // 0xE910 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_18;                                 // 0xE940 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_17;                                 // 0xE9F8 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_16;                                 // 0xEAB0 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_15;                                 // 0xEB68 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_14;                                 // 0xEC20 (size: 0xB8)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_2;                        // 0xECD8 (size: 0xB0)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_13;                                 // 0xED88 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_12;                                 // 0xEE40 (size: 0xB8)
    FAnimNode_BlendListByInt AnimGraphNode_BlendListByInt;                            // 0xEEF8 (size: 0xA0)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_1;                        // 0xEF98 (size: 0xB0)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_11;                                 // 0xF048 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_10;                                 // 0xF100 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_9;                                  // 0xF1B8 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_8;                                  // 0xF270 (size: 0xB8)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_7;                                  // 0xF328 (size: 0xB8)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;                          // 0xF3E0 (size: 0xB0)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers_1;    // 0xF490 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_12;                               // 0xF560 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_6;                                  // 0xF590 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_11;                               // 0xF648 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_5;                              // 0xF678 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_10;                               // 0xF728 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;                      // 0xF758 (size: 0x28)
    FSCAnimNode_SetVariableWeightLayers SCAnimGraphNode_SetVariableWeightLayers;      // 0xF780 (size: 0xD0)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;                      // 0xF850 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;                      // 0xF878 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;                      // 0xF8A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;                      // 0xF8C8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;                      // 0xF8F0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;                      // 0xF918 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_5;                                  // 0xF940 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_9;                                // 0xF9F8 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_4;                                  // 0xFA28 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_8;                                // 0xFAE0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_4;                              // 0xFB10 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_7;                                // 0xFBC0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;                      // 0xFBF0 (size: 0x28)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_3;                                  // 0xFC18 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_6;                                // 0xFCD0 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_2;                                  // 0xFD00 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_5;                                // 0xFDB8 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_3;                              // 0xFDE8 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_4;                                // 0xFE98 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim_1;                                  // 0xFEC8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_3;                                // 0xFF80 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;                        // 0xFFB0 (size: 0x28)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_2;                              // 0xFFD8 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_2;                                // 0x10088 (size: 0x30)
    FSCAnimNode_PlayAnim SCAnimGraphNode_PlayAnim;                                    // 0x100B8 (size: 0xB8)
    FAnimNode_StateResult AnimGraphNode_StateResult_1;                                // 0x10170 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_1;                              // 0x101A0 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult;                                  // 0x10250 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine;                                // 0x10280 (size: 0xB0)
    FAnimNode_Root AnimGraphNode_Root;                                                // 0x10330 (size: 0x30)
    FSCAnimNode_MultiVariableWeightBlender SCAnimGraphNode_MultiVariableWeightBlender; // 0x10360 (size: 0xC8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;                          // 0x10428 (size: 0xA0)
    FAnimNode_PoseSnapshot AnimGraphNode_PoseSnapshot;                                // 0x104C8 (size: 0x90)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend;                        // 0x10558 (size: 0xC0)
    FSCAnimNode_PlayBlendSpace SCAnimGraphNode_PlayBlendSpace;                        // 0x10618 (size: 0x110)
    FSCAnimNode_SaveBoneTransformByName SCAnimGraphNode_SaveBoneTransformByName;      // 0x10728 (size: 0x58)
    FAnimNode_TwoBoneIK AnimGraphNode_TwoBoneIK_1;                                    // 0x10780 (size: 0x1E0)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;       // 0x10960 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;       // 0x10980 (size: 0x20)
    FAnimNode_TwoBoneIK AnimGraphNode_TwoBoneIK;                                      // 0x109A0 (size: 0x1E0)
    bool __CustomProperty_Mirror_B5BEA22547DED4A32D6BDEBB5849E17B;                    // 0x10B80 (size: 0x1)
    float __CustomProperty_ShakePelvisAlpha_825F74DE42243145FA989983E6E6630B;         // 0x10B84 (size: 0x4)
    FVector __CustomProperty_ShakePelvisOffset_825F74DE42243145FA989983E6E6630B;      // 0x10B88 (size: 0xC)
    float __CustomProperty_LandingAlpha_825F74DE42243145FA989983E6E6630B;             // 0x10B94 (size: 0x4)
    class AFightingCharacter* BP_FightCharacter_Reference;                            // 0x10B98 (size: 0x8)
    bool DebugAimIK;                                                                  // 0x10BA0 (size: 0x1)
    float MaxAimYawInLockMove;                                                        // 0x10BA4 (size: 0x4)
    float MaxAimYawInFreeMove;                                                        // 0x10BA8 (size: 0x4)
    float VelocityMaxForV1Anim;                                                       // 0x10BAC (size: 0x4)
    float VelocityMaxForV2Anim;                                                       // 0x10BB0 (size: 0x4)
    float Dt;                                                                         // 0x10BB4 (size: 0x4)
    FVector TraceOffset;                                                              // 0x10BB8 (size: 0xC)
    float ForwardFloorAngle;                                                          // 0x10BC4 (size: 0x4)
    bool FreemoveAsLockmove;                                                          // 0x10BC8 (size: 0x1)
    float Preview_VelocityLength;                                                     // 0x10BCC (size: 0x4)
    float Preview_VelocityAngle;                                                      // 0x10BD0 (size: 0x4)
    TSubclassOf<class ABaseWeapon> Preview_EquipWeapon;                               // 0x10BD8 (size: 0x8)
    class ABaseWeapon* Debug_WeaponEquipped;                                          // 0x10BE0 (size: 0x8)
    bool Preview_Init_Done;                                                           // 0x10BE8 (size: 0x1)
    bool Preview_FreemoveAsLockMove;                                                  // 0x10BE9 (size: 0x1)
    bool Preview_IsInCombat;                                                          // 0x10BEA (size: 0x1)
    FBlendSpaceContainer Weapon_V1_BlendSpace_front_tense;                            // 0x10BF0 (size: 0x10)
    FBlendSpaceContainer Weapon_V1_BlendSpace_back_tense;                             // 0x10C00 (size: 0x10)
    TSubclassOf<class UBaseWeaponData> Preview_OverrideWeaponData;                    // 0x10C10 (size: 0x8)
    TSubclassOf<class UBaseWeaponData> Debug_OverrideWeaponDataLastFrame;             // 0x10C18 (size: 0x8)
    FAnimContainer Weapon_V0_FL_tense;                                                // 0x10C20 (size: 0x18)
    FAnimContainer Weapon_V0_FR_tense;                                                // 0x10C38 (size: 0x18)
    FAnimContainer Weapon_V0_Freemove;                                                // 0x10C50 (size: 0x18)
    class UBlendProfile* Weapon_V1_Idle_BlendProfile;                                 // 0x10C68 (size: 0x8)
    class UBlendProfile* Weapon_V0_Idle_BlendProfile;                                 // 0x10C70 (size: 0x8)
    class UBlendProfile* Weapon_V2_Idle_BlendProfile;                                 // 0x10C78 (size: 0x8)
    class UBlendProfile* Weapon_V3_Idle_BlendProfile;                                 // 0x10C80 (size: 0x8)
    class UBlendProfile* Weapon_V0_Action_BlendProfile;                               // 0x10C88 (size: 0x8)
    class UBlendProfile* Weapon_V1_Action_Floor_BlendProfile;                         // 0x10C90 (size: 0x8)
    class UBlendProfile* Weapon_V1_Action_Mid_BlendProfile;                           // 0x10C98 (size: 0x8)
    class UBlendProfile* Weapon_V2_Action_BlendProfile;                               // 0x10CA0 (size: 0x8)
    class UBlendProfile* Weapon_V3_Action_BlendProfile;                               // 0x10CA8 (size: 0x8)
    class UBlendProfile* Weapon_V0_Idle_Freemove_BlendProfile;                        // 0x10CB0 (size: 0x8)
    FBlendSpaceContainer Weapon_V2_BlendSpace_front;                                  // 0x10CB8 (size: 0x10)
    FBlendSpaceContainer Weapon_V2_BlendSpace_back;                                   // 0x10CC8 (size: 0x10)
    FBlendSpaceContainer Weapon_V3_BlendSpace_front;                                  // 0x10CD8 (size: 0x10)
    FBlendSpaceContainer Weapon_V3_BlendSpace_back;                                   // 0x10CE8 (size: 0x10)
    class UBlendProfile* Weapon_V0_HandSwap_BlendProfile;                             // 0x10CF8 (size: 0x8)
    FAnimStructVariableWeight Preview_Gesture;                                        // 0x10D00 (size: 0x90)
    TEnumAsByte<BP_AvoidType> avoidType;                                              // 0x10D90 (size: 0x1)
    float AlphaStateFly;                                                              // 0x10D94 (size: 0x4)
    float CurrentVelocityForward;                                                     // 0x10D98 (size: 0x4)
    FRotator VelocityRotator;                                                         // 0x10D9C (size: 0xC)
    FVector previousForwardVector;                                                    // 0x10DA8 (size: 0xC)
    FVector CurrentForwardVector;                                                     // 0x10DB4 (size: 0xC)
    float CurrentDeltaAngle;                                                          // 0x10DC0 (size: 0x4)
    FRotator LastForwardRotator;                                                      // 0x10DC4 (size: 0xC)
    FVector TranslationUpdate;                                                        // 0x10DD0 (size: 0xC)
    class UBlendProfile* OpeningDoorBothHands_V0_BlendProfile;                        // 0x10DE0 (size: 0x8)
    class UBlendProfile* OpeningDoorBothHands_V1_BlendProfile;                        // 0x10DE8 (size: 0x8)
    class UBlendProfile* OpeningDoorBothHands_V2_BlendProfile;                        // 0x10DF0 (size: 0x8)
    class UBlendProfile* OpeningDoorBothHands_V3_BlendProfile;                        // 0x10DF8 (size: 0x8)
    class UBlendProfile* FidgetBlendProfileV0;                                        // 0x10E00 (size: 0x8)
    class UBlendProfile* FidgetBlendProfileV1;                                        // 0x10E08 (size: 0x8)
    class UBlendProfile* FidgetBlendProfileV2;                                        // 0x10E10 (size: 0x8)
    class UBlendProfile* FidgetBlendProfileV3;                                        // 0x10E18 (size: 0x8)
    class UBlendProfile* OpeningDoorRightHand_V0_BlendProfile;                        // 0x10E20 (size: 0x8)
    class UBlendProfile* OpeningDoorRightHand_V1_BlendProfile;                        // 0x10E28 (size: 0x8)
    class UBlendProfile* OpeningDoorRightHand_V2_BlendProfile;                        // 0x10E30 (size: 0x8)
    class UBlendProfile* OpeningDoorRightHand_V3_BlendProfile;                        // 0x10E38 (size: 0x8)
    bool Preview_LaunchDoor;                                                          // 0x10E40 (size: 0x1)
    FAnimContainer Preview_DoorAnim;                                                  // 0x10E48 (size: 0x18)
    FAnimContainer Debug_LastDoorAnim;                                                // 0x10E60 (size: 0x18)
    float Debug_LastDoorLaunchTimer;                                                  // 0x10E78 (size: 0x4)
    TEnumAsByte<VariableWeightLayers> Preview_DoorVariableWeightLayer;                // 0x10E7C (size: 0x1)
    int32 Debug_DoorSubAnimState;                                                     // 0x10E80 (size: 0x4)
    bool Debug_EarlyBlendOutFired;                                                    // 0x10E84 (size: 0x1)
    TEnumAsByte<VariableWeightLayers> Debug_DoorVariableWeightLayer;                  // 0x10E85 (size: 0x1)
    bool bIsGrounded;                                                                 // 0x10E86 (size: 0x1)
    bool bIsInLocomotion;                                                             // 0x10E87 (size: 0x1)
    TArray<ESpeedState> DirtyVariableWeightInfos;                                     // 0x10E88 (size: 0x10)
    FVariableWeightInfo VariableWeightInfoV0;                                         // 0x10E98 (size: 0x20)
    FVariableWeightInfo VariableWeightInfoV1;                                         // 0x10EB8 (size: 0x20)
    FVariableWeightInfo VariableWeightInfoV2;                                         // 0x10ED8 (size: 0x20)
    FVariableWeightInfo VariableWeightInfoV3;                                         // 0x10EF8 (size: 0x20)
    class UBlendProfile* Weapon_V0_Action_Mid_BlendProfile;                           // 0x10F18 (size: 0x8)
    class UBlendProfile* Weapon_V2_Action_Mid_BlendProfile;                           // 0x10F20 (size: 0x8)
    class UBlendProfile* Weapon_V3_Action_Mid_BlendProfile;                           // 0x10F28 (size: 0x8)
    FVector TestLookAtTarget;                                                         // 0x10F30 (size: 0xC)
    class UBlendSpaceBase* Eyes Look at Blend Space;                                  // 0x10F40 (size: 0x8)
    float CinematicRightHandIk;                                                       // 0x10F48 (size: 0x4)
    float CinematicLeftHandIk;                                                        // 0x10F4C (size: 0x4)
    FVector CinematicRightHandEffectorOffset;                                         // 0x10F50 (size: 0xC)
    FVector CinematicLeftHandEffectorOffset;                                          // 0x10F5C (size: 0xC)
    bool WeaponFootPickup;                                                            // 0x10F68 (size: 0x1)
    class UBlendProfile* OpeningDoorRightHandV0WithWeaponBlendProfile;                // 0x10F70 (size: 0x8)
    class UBlendProfile* OpeningDoorBothHandsV0WithWeaponBlendProfile;                // 0x10F78 (size: 0x8)
    FVariableWeightInfo GuardVWInfo;                                                  // 0x10F80 (size: 0x20)
    FVariableWeightInfo TraversalVWInfo;                                              // 0x10FA0 (size: 0x20)

    void AnimGraph(FPoseLink& AnimGraph);
    void GetVariableWeightInfoByLayer(ESpeedState ESpeedState, TEnumAsByte<VariableWeightLayers> InLayer, EMoveStatus MoveStatus, class UBlendProfile*& BlendProfile);
    void Internal_SetWeaponMovingBlendSpaces(ESpeedState InSpeedState, const FBlendSpaceContainer& InFrontBlendSpace, FBlendSpaceContainer InBackBlendSpace);
    void Internal_UpdateVariableWeightInfoBySpeedState(ESpeedState InSpeedState);
    void Internal_SetBlendProfileBySpeedState(ESpeedState InSpeedState, TEnumAsByte<VariableWeightLayers> InLayer, EMoveStatus InMoveStatus, class UBlendProfile* InBlendProfile, bool bImmediateUpdate);
    void ComputeFlyModeVariables();
    void InitPreviewing();
    void UpdateFromPreviewValues(float DeltaTime);
    void CalculateForwardFloorAngle();
    void IsInTransition(bool& InTransition);
    void IsInUTurnTransition(bool& InTransition);
    void IsInStopTransition(bool& InTransition);
    void IsInStartTransition(bool& InTransition);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TwoWayBlend_FDE39E2B41EA79B8E89FE389EC2951A9();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_48A325B44601B2A2B491159E3890B40E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_F418C59B4DD89517F9EF229A0D62555E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_BlendListByBool_2A2EA2F84C722C76882D91BD70240E88();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_6854F3CC4EB441BAC9B8CBB4DD6B0788();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_6CA506E24C23D2188435AD9A0894B69F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_D74A28214BD004E821073A95E7A0A271();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_502CFFFE4080976E2B6AE1828D51D623();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_E1C797484FAD71C2E4C7389D91C56898();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_662C61564E8435E7EC3E1FBB1F564E63();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_9C32BB374D4FD3B7C33967A878F5ACDA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_B76268714340CFA4C0AD9A9004C1343F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_3D4BD5D94DF94AA5B1C96C92D478DA35();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_26B603B04179595798F31EB751FC88CA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_538EC69146C8704963754ABA80BEB334();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_SetVariableWeightLayers_EFD6E0D343CC73AA544AE5909D0E5D2D();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_46DDC64D424CFDFFDE4171925D2B6198();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_9436EA604A8130E64CC7298B5A174D77();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_BF41A70C46FD7B6351299280D7A44C5F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_BA8166544780442336875180AD8E9812();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_452108EF4E82CDC832C7EA8129FEB195();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_7FBB445941DC37649F3F36A67F693553();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_62CB780541F922D6DB87F0A5B7D2EECB();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_1E83F7A7478CB76A1BDDBBAF8FAB1C93();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_38FBEE8D4D9C4DC4801676B0B8E5610B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_0C1380F94D63449A0E5F4EA69C31728E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_A8AED719485C09112A0A7F88018BCDE7();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_96B1A15D4FA248483DBF298BBC3BA570();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_LinkedAnimGraph_B5BEA22547DED4A32D6BDEBB5849E17B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_7DD32D9D45C3B2285E6C7CA6CF6B78DD();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_A137CFB243E7E92037B232935745734D();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_9CA1C19742FDBBB5BA0A4DBBD32B6C5A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_97A54C45468617C65A7714BBCF1FB23F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_SCAnimGraphNode_PlayAnim_DD500FC64B7145037B84A6BC82DA0AC0();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_5800AA9A4120FB9C9067B2911D7171B6();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_68A21F074F3AAFA5F8B57986D6CACDB1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_14336BAF4D1DAF086E63CDBB6B832CB7();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_980E882D42CB312D6C94B8B3FA1DA5E6();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_18F1D3F84312F8CF841061AE0BE2FC00();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_D03C2E914DC6A8373F96D08AED090398();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_9F8D44E44380A95208019685F39A91F5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_39CBB16144F5444E4AE4FFB7AC6B4EDF();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_4B22E3CE4FCF40B1088B5582B26D117C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_F33CA1D447898E06BBDAE9A4E20A6CE7();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_8E7AE3B54FCDC75049B259A67A04B3F0();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_46C5ED09429CFAEE4BD834AC6AA4195F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_66C11A55407C90C4E1E3D089A24D179E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_F981EC22463BAE9AF0F383960B9B2F5C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_Wuguan_Character_AnimationBlueprint_AnimGraphNode_TransitionResult_8980E621456F5D9C583921B1A17348E5();
    void BlueprintInitializeAnimation();
    void BlueprintPostEvaluateAnimation();
    void CustomEvent();
    void m_OnStarting_Event_0(uint8 _ID, class UOrderComponent* _OrderComponent);
    void BPE_OnCinematicBlendOut();
    void AnimNotify_Preview_EarlyBlendOut();
    void BPE_UpdateAnimationInPreview(float _fDt);
    void BPE_OnMoveStatusChanged();
    void SetBlendProfileBySpeedState(ESpeedState InSpeedState, TEnumAsByte<VariableWeightLayers> InViriableWeightLayer, EMoveStatus InMoveStatus, class UBlendProfile* InBlendProfile, bool bImmediateUpdate);
    void UpdateAllInvalidatedVariableWeightInfo();
    void InvalidateAllVariableWeightInfo();
    void UpdateVariableWeightInfoBySpeedState(ESpeedState InSpeedState);
    void SetWeaponV0Anims(FAnimContainer InFrontLeftCombat, FAnimContainer InFrontRightCombat, FAnimContainer InFrontLeftFreeMove);
    void SetWeaponMovingBlendSpaces(ESpeedState InSpeedState, FBlendSpaceContainer InFrontBlendSpaceDirection, FBlendSpaceContainer InBackBlendSpaceDirection);
    void BPE_UpdateForVLog();
    void BPE_OnCinematicBlendedOut();
    void AnimNotify_FallingStateStart();
    void AnimNotify_FallingStateStop();
    void ExecuteUbergraph_Wuguan_Character_AnimationBlueprint(int32 EntryPoint);
}; // Size: 0x10FC0

#endif
